/**
 * RenameSymbol end to end with the real bundled typescript-language-server:
 * a rename across files is one all-or-nothing write, previews write nothing,
 * a forbidden file refuses the whole rename, and a colliding name is flagged
 * by the post-write diagnostics.
 */
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'fs';
import { createRequire } from 'module';
import { tmpdir } from 'os';
import path from 'path';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { createLanguageServerDiagnosticsProvider } from '../../providers/pi-runtime/language-server-diagnostics.js';
import { buildTools } from '../../providers/pi-runtime/tool-bridge.js';
import { LanguageServerManager } from '../manager.js';

const require = createRequire(import.meta.url);
const typescriptPackage = path.dirname(require.resolve('typescript/package.json'));

async function until(check: () => boolean, timeoutMs: number): Promise<void> {
  const started = Date.now();
  while (!check()) {
    if (Date.now() - started > timeoutMs) throw new Error('timed out waiting');
    await new Promise(resolve => setTimeout(resolve, 50));
  }
}

describe('RenameSymbol (real language server)', () => {
  let root: string;
  let manager: LanguageServerManager;
  let lease: { release(): void };
  let rename: any;
  const read = (file: string) => readFileSync(path.join(root, file), 'utf8');
  const write = (file: string, content: string) => writeFileSync(path.join(root, file), content);

  beforeAll(async () => {
    root = mkdtempSync(path.join(tmpdir(), 'lsp-rename-'));
    mkdirSync(path.join(root, 'node_modules'));
    mkdirSync(path.join(root, 'src'));
    symlinkSync(typescriptPackage, path.join(root, 'node_modules', 'typescript'), 'dir');
    write('package.json', '{"name":"p","private":true}');
    write(
      'tsconfig.json',
      JSON.stringify({ compilerOptions: { strict: true, noEmit: true }, include: ['src'] })
    );
    manager = new LanguageServerManager();
    lease = manager.acquire(root, 'test');
    await until(() => manager.status().some(s => s.state === 'ready'), 30_000);
    rename = buildTools(root, {
      enabled: ['RenameSymbol'],
      languageServerPort: manager,
      diagnosticsProvider: createLanguageServerDiagnosticsProvider(manager, root, 15_000),
    }).find(tool => tool.name === 'RenameSymbol');
  });

  afterAll(async () => {
    lease.release();
    await manager.dispose();
    rmSync(root, { recursive: true, force: true });
  });

  beforeEach(() => {
    write('src/lib.ts', 'export function greet(name: string): string {\n  return name;\n}\n');
    // CRLF line endings must survive untouched.
    write('src/a.ts', "import { greet } from './lib';\r\nexport const a = greet('a');\r\n");
    write(
      'src/b.ts',
      "import { greet } from './lib';\n\nexport const b = greet('b') + greet('c');\n"
    );
    rmSync(path.join(root, 'src', 'gen.ts'), { force: true });
  });

  it('is registered with a language server that can rename', () => {
    expect(rename).toBeDefined();
  });

  it('previews without writing anything', async () => {
    const res = await rename.execute('r0', {
      file_path: 'src/lib.ts',
      line: 1,
      symbol: 'greet',
      new_name: 'welcome',
      preview_only: true,
    });
    expect(res.details).toMatchObject({ ok: true, preview: true, fileCount: 3 });
    expect(res.content[0].text).toContain('Previewed rename greet → welcome');
    expect(read('src/b.ts')).toContain('greet');
  }, 60_000);

  it('renames every reference across files in one call, with no new errors', async () => {
    const res = await rename.execute('r1', {
      file_path: 'src/b.ts',
      line: 3,
      symbol: 'greet',
      occurrence: 2,
      new_name: 'welcome',
    });
    expect(res.details).toMatchObject({ ok: true, fileCount: 3, editCount: 6 });
    const text = res.content[0].text as string;
    expect(text).toContain('Renamed greet → welcome');
    expect(text).toContain('Files changed: 3');
    expect(text).toContain('Diagnostics (TypeScript): no new errors');
    expect(read('src/lib.ts')).toBe(
      'export function welcome(name: string): string {\n  return name;\n}\n'
    );
    expect(read('src/a.ts')).toBe(
      "import { welcome } from './lib';\r\nexport const a = welcome('a');\r\n"
    );
    expect(read('src/b.ts')).toBe(
      "import { welcome } from './lib';\n\nexport const b = welcome('b') + welcome('c');\n"
    );
    expect(res.details.perFileResults.every((file: any) => file.backup?.id)).toBe(true);
  }, 60_000);

  it('refuses the whole rename when a reference is in an auto-generated file', async () => {
    write(
      'src/gen.ts',
      "// @generated by a tool\nimport { greet } from './lib';\nexport const g = greet('g');\n"
    );
    const res = await rename.execute('r2', {
      file_path: 'src/lib.ts',
      line: 1,
      symbol: 'greet',
      new_name: 'welcome',
    });
    expect(res.details).toMatchObject({ ok: false, error: 'rename_refused' });
    expect(res.content[0].text).toContain('src/gen.ts (auto-generated)');
    expect(read('src/lib.ts')).toContain('function greet');
    expect(read('src/a.ts')).toContain('greet');
  }, 60_000);

  it('flags a name that collides with another symbol', async () => {
    write(
      'src/lib.ts',
      'export function greet(name: string): string {\n  return name;\n}\nexport const other = 1;\n'
    );
    const res = await rename.execute('r3', {
      file_path: 'src/lib.ts',
      line: 1,
      symbol: 'greet',
      new_name: 'other',
    });
    const text = res.content[0].text as string;
    expect(text).toMatch(/new errors? introduced/);
    expect(text).toContain('collides with or shadows');
  }, 60_000);

  it('says why a position cannot be renamed', async () => {
    const res = await rename.execute('r4', {
      file_path: 'src/lib.ts',
      line: 1,
      symbol: 'string',
      new_name: 'text',
    });
    expect(res.details).toMatchObject({ ok: false, error: 'rename_not_allowed' });
  }, 60_000);
});
