/**
 * The Edit bridge tool: exact single/batch replacements in one workspace
 * file, plus the apply_patch-style multi-file path dispatched when the
 * caller passes `patch`. Handles read-state guards (including stale-read
 * rebasing), hashline-anchored edits, whitespace-normalized matching, the
 * noop-edit loop guard, backups, and write lifecycle hooks.
 */

import type { AgentTool } from '@earendil-works/pi-agent-core';
import { mkdir, rename, rm, stat } from 'fs/promises';
import * as path from 'path';

import { buildAutoGeneratedMessage, findAutoGeneratedMarker } from '../auto-generated-guard.js';
import { parseApplyPatch } from '../apply-patch.js';
import { buildFileDiff } from '../diff.js';
import {
  applyEdit,
  countOccurrences,
  findActualString,
  findWhitespaceMatch,
} from '../edit-match.js';
import {
  buildFileStateErrorDescriptor,
  buildMutationStateDescriptor,
} from '../file-state.js';
import { recordFileBackup } from '../file-history.js';
import { runWithFileWriteLock } from '../file-write-lock.js';
import {
  hashlineForLine,
  hashlineTag,
  parseHashlineOperation,
  replaceHashlineLine,
} from '../hashline.js';
import { NOOP_EDIT_HARD_LIMIT } from '../noop-edit-guard.js';
import {
  applyLineEndingStyle,
  lineEndingFor,
  readTextFileWithMetadata,
  writeTextFileAtomic,
} from '../text-io.js';
import { MAX_EDIT_FILE_BYTES, validateMutationContent } from '../write-guards.js';
import {
  mergeWriteLifecycleResults,
  runDiagnosticsProvider,
  runWriteLifecycle,
  scheduleDeferredDiagnostics,
} from '../write-lifecycle.js';
import { resolveInsideWorkspace, toWorkspaceRelative } from '../workspace-paths.js';
import {
  buildMutationDetailsBase,
  buildMutationResultText,
  truncateDiffDetail,
} from './mutation-details.js';
import { createWriteBridgeTool } from './write-tool.js';
import {
  assertRebaseAnchorsWereRead,
  errorResult,
  firstPatchFailurePath,
  guardErrorDetails,
  parseBatchEdits,
  readGuardFailureDetails,
  resolveWritePath,
  resultDetails,
  runWithFileWriteLocks,
  textResult,
  toolParams,
  validateUpdatedContent,
  type FileMutationToolOptions,
  type MutationDetails,
} from './shared.js';

export function createEditBridgeTool(cwd: string, options?: FileMutationToolOptions): AgentTool {
  return {
    name: 'Edit',
    label: 'Edit',
    description:
      'Replace one exact string in an existing file. For two or more replacements in the same file, use MultiEdit so the file is read, checked, and written once; the batch is atomic and counts as one mutation attempt. This tool still accepts an `edits` array for compatibility, but new same-file batches should prefer MultiEdit. For small multi-file changes, use `patch`. For structurally-sensitive rewrites (Markdown tables, JSON arrays, indented YAML/TOML), prefer a single Write. Successful mutation results include a model-visible diff plus snapshot state, and update the internal file snapshot, so do not call Read again only to verify the edit.',
    parameters: {
      type: 'object',
      properties: {
        file_path: {
          type: 'string',
          description:
            'Workspace-relative path of the file to edit (required unless `patch` is given)',
        },
        old_string: {
          type: 'string',
          description:
            'Exact text to replace (required unless `patch` or `hashline_operation` is given)',
        },
        new_string: {
          type: 'string',
          description: 'Replacement text (required unless `patch` is given)',
        },
        replace_all: { type: 'boolean', default: false },
        edits: {
          type: 'array',
          description:
            'Compatibility path for same-file batch replacements. Prefer MultiEdit for two or more replacements in one file; all replacements apply atomically and consume one mutation attempt.',
          minItems: 1,
          items: {
            type: 'object',
            properties: {
              old_string: { type: 'string' },
              new_string: { type: 'string' },
              replace_all: { type: 'boolean', default: false },
            },
            required: ['old_string', 'new_string'],
          },
        },
        patch: {
          type: 'string',
          description:
            'Optional apply_patch-style multi-file patch. When provided, file_path/old_string/new_string are ignored. Operations apply sequentially and are NOT atomic: a failure partway leaves earlier operations already written to disk (reported as patch_partial_failure). Real runs are preflighted automatically; pass preview_only:true for an explicit dry run before a risky patch.',
        },
        preview_only: {
          type: 'boolean',
          default: false,
          description:
            'When true, validate the edit and compute the diff without writing to disk or updating the snapshot (dry run).',
        },
        hashline_line: {
          type: 'string',
          description: 'Optional line hash from Read(hashline:true)',
        },
        hashline_operation: {
          type: 'string',
          description: 'Optional hashline operation, such as replace:<line-hash>',
        },
        hashline_tag: {
          type: 'string',
          description: 'Optional file-level tag from Read(hashline:true)',
        },
      },
    },
    execute: async (toolCallId: string, params: unknown) => {
      const args = toolParams(toolCallId, params);
      if (typeof args.patch === 'string' && args.patch.trim()) {
        try {
          const operations = parseApplyPatch(args.patch);
          const perFileResults: MutationDetails[] = [];
          const previewOnly = args.preview_only === true;
          if (!previewOnly) {
            // Preflight runs with the noop guard disabled: it is a speculative
            // dry run, so failures inside it must not count toward
            // NOOP_EDIT_HARD_LIMIT — only the real run records its own. A
            // failed preflight short-circuits the real run, so record the
            // failed patch once here (keyed by patch content, so an adjusted
            // patch starts fresh) to keep the edit-loop protection intact.
            const preflightTool = createEditBridgeTool(cwd, { ...options, noopGuard: undefined });
            const preflight = await preflightTool.execute(`${toolCallId}:preflight`, {
              patch: args.patch,
              preview_only: true,
            });
            const preflightDetails = resultDetails(preflight);
            if (preflightDetails.ok === false) {
              const failurePath = firstPatchFailurePath(preflightDetails);
              const attempts = options?.noopGuard
                ? options.noopGuard.record(
                    failurePath ? path.resolve(cwd, failurePath) : cwd,
                    `patch_failed:${hashlineForLine(args.patch)}`
                  )
                : 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This patch has failed preflight ${attempts} times` +
                    (failurePath ? ` (last failure in ${failurePath})` : '') +
                    '. Read the file again to see its current content before retrying.',
                  {
                    ...(failurePath ? { path: failurePath } : {}),
                    attempts,
                    ...(preflightDetails.perFileResults
                      ? { perFileResults: preflightDetails.perFileResults }
                      : {}),
                  }
                );
              }
              return textResult(
                buildMutationResultText({
                  action: 'Patch failed preflight',
                  perFileResults: preflightDetails.perFileResults,
                  diff:
                    typeof preflightDetails.diff === 'string' ? preflightDetails.diff : undefined,
                  snapshotUpdated: false,
                }),
                {
                  ...preflightDetails,
                  preview: false,
                }
              );
            }
          }
          for (const operation of operations) {
            if (operation.type === 'add') {
              let filePath: string;
              try {
                filePath = resolveInsideWorkspace(cwd, operation.path);
              } catch (err) {
                const failure = {
                  ok: false,
                  error: 'path_outside_workspace',
                  message: err instanceof Error ? err.message : String(err),
                  path: operation.path,
                  type: 'create',
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              }
              const relPath = toWorkspaceRelative(cwd, filePath);
              const contentGuard = validateMutationContent(filePath, operation.content);
              if (contentGuard) {
                const failure = {
                  ok: false,
                  error: contentGuard.code,
                  message: contentGuard.message,
                  path: relPath,
                  type: 'create',
                  ...(contentGuard.details ?? {}),
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              }
              const filenameMarker = findAutoGeneratedMarker(filePath, null);
              if (filenameMarker) {
                const failure = {
                  ok: false,
                  error: 'auto_generated_file',
                  message: buildAutoGeneratedMessage(relPath, filenameMarker),
                  path: relPath,
                  type: 'create',
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              }
              let existed = false;
              let originalContent: string | null = null;
              try {
                // Symlinks are followed through to their target by the Write
                // tool (and by resolveWritePath); stat() here follows the link.
                const targetStat = await stat(filePath);
                if (!targetStat.isFile()) {
                  const failure = {
                    ok: false,
                    error: 'not_a_file',
                    message: `Path is not a file: ${relPath}`,
                    path: relPath,
                    type: 'create',
                  };
                  if (perFileResults.length === 0) return textResult(failure.message, failure);
                  perFileResults.push(failure);
                  break;
                }
                existed = true;
                const originalMetadata = await readTextFileWithMetadata(filePath);
                originalContent = originalMetadata.content;
                const generatedMarker = findAutoGeneratedMarker(filePath, originalContent);
                if (generatedMarker) {
                  const failure = {
                    ok: false,
                    error: 'auto_generated_file',
                    message: buildAutoGeneratedMessage(relPath, generatedMarker),
                    path: relPath,
                    type: 'create',
                  };
                  if (perFileResults.length === 0) return textResult(failure.message, failure);
                  perFileResults.push(failure);
                  break;
                }
                const readCheck = await options?.readFileState?.assertSafeToWrite(
                  filePath,
                  originalContent
                );
                if (readCheck && !readCheck.ok) {
                  const failure = {
                    ok: false,
                    error: readCheck.code,
                    message: readCheck.message,
                    path: relPath,
                    type: 'create',
                  };
                  if (perFileResults.length === 0) return textResult(failure.message, failure);
                  perFileResults.push(failure);
                  break;
                }
              } catch (err) {
                if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
              }
              if (previewOnly) {
                const diff = buildFileDiff(relPath, originalContent ?? '', operation.content);
                perFileResults.push({
                  ...buildMutationDetailsBase({
                    path: relPath,
                    diff,
                    extra: {
                      preview: true,
                      type: existed ? 'update' : 'create',
                    },
                  }),
                  preview: true,
                  type: existed ? 'update' : 'create',
                  path: relPath,
                });
                continue;
              }
              const writeTool = createWriteBridgeTool(cwd, options);
              const result = await writeTool.execute(`${toolCallId}:add:${operation.path}`, {
                file_path: operation.path,
                content: operation.content,
              });
              const details = resultDetails(result);
              if (details.ok === false) {
                if (perFileResults.length === 0) return result;
                perFileResults.push({ ...details, path: operation.path });
                break;
              }
              perFileResults.push({ ...details, path: operation.path });
              continue;
            }
            if (operation.type === 'delete') {
              const filePath = resolveInsideWorkspace(cwd, operation.path);
              const originalMetadata = await readTextFileWithMetadata(filePath);
              const original = originalMetadata.content;
              const generatedMarker = findAutoGeneratedMarker(filePath, original);
              if (generatedMarker) {
                const message = buildAutoGeneratedMessage(operation.path, generatedMarker);
                const failure = {
                  ok: false,
                  error: 'auto_generated_file',
                  message,
                  path: operation.path,
                  type: 'delete',
                };
                if (perFileResults.length === 0) return textResult(message, failure);
                perFileResults.push(failure);
                break;
              }
              const readCheck = await options?.readFileState?.assertSafeToWrite(filePath, original);
              if (readCheck && !readCheck.ok) {
                const failure = {
                  ok: false,
                  error: readCheck.code,
                  message: readCheck.message,
                  path: operation.path,
                  type: 'delete',
                };
                if (perFileResults.length === 0) return textResult(readCheck.message, failure);
                perFileResults.push(failure);
                break;
              }
              const diff = buildFileDiff(operation.path, original, '');
              const backup = previewOnly
                ? undefined
                : await recordFileBackup(operation.path, original, filePath);
              if (!previewOnly) {
                await runWithFileWriteLock(filePath, async () => {
                  await rm(filePath);
                });
                options?.noopGuard?.clear(filePath);
              }
              perFileResults.push({
                ...buildMutationDetailsBase({
                  path: operation.path,
                  diff,
                  extra: {
                    ...(previewOnly ? { preview: true } : {}),
                    type: 'delete',
                    ...(backup ? { backup } : {}),
                  },
                }),
                ...(previewOnly ? { preview: true } : {}),
                type: 'delete',
                path: operation.path,
                ...(backup ? { backup } : {}),
              });
              continue;
            }
            if (operation.type === 'rename') {
              const fromPath = resolveInsideWorkspace(cwd, operation.from);
              const toPath = resolveInsideWorkspace(cwd, operation.to);
              try {
                await stat(toPath);
                const failure = {
                  ok: false,
                  error: 'target_exists',
                  message: `Rename target already exists: ${operation.to}`,
                  path: operation.to,
                  originalPath: operation.from,
                  type: 'rename',
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              } catch {
                // Target does not exist, so rename is allowed.
              }
              const originalMetadata = await readTextFileWithMetadata(fromPath);
              const original = originalMetadata.content;
              const generatedMarker = findAutoGeneratedMarker(fromPath, original);
              if (generatedMarker) {
                const message = buildAutoGeneratedMessage(operation.from, generatedMarker);
                const failure = {
                  ok: false,
                  error: 'auto_generated_file',
                  message,
                  path: operation.to,
                  originalPath: operation.from,
                  type: 'rename',
                };
                if (perFileResults.length === 0) return textResult(message, failure);
                perFileResults.push(failure);
                break;
              }
              const readCheck = await options?.readFileState?.assertSafeToWrite(fromPath, original);
              if (readCheck && !readCheck.ok) {
                const failure = {
                  ok: false,
                  error: readCheck.code,
                  message: readCheck.message,
                  path: operation.to,
                  originalPath: operation.from,
                  type: 'rename',
                };
                if (perFileResults.length === 0) return textResult(readCheck.message, failure);
                perFileResults.push(failure);
                break;
              }
              const backup = previewOnly
                ? undefined
                : await recordFileBackup(operation.from, original, fromPath);
              if (!previewOnly) {
                await runWithFileWriteLocks([fromPath, toPath], async () => {
                  await mkdir(path.dirname(toPath), { recursive: true });
                  await rename(fromPath, toPath);
                });
                await options?.readFileState?.recordWrite(toPath, original);
                options?.noopGuard?.clear(fromPath);
                options?.noopGuard?.clear(toPath);
              }
              perFileResults.push({
                ok: true,
                ...(previewOnly ? { preview: true } : {}),
                type: 'rename',
                path: operation.to,
                originalPath: operation.from,
                updatedContent: original,
                ...(backup ? { backup } : {}),
              });
              continue;
            }
            const editTool = createEditBridgeTool(cwd, options);
            const runUpdate = (oldText: string, newText: string, attempt: string) =>
              editTool.execute(`${toolCallId}:update:${operation.path}${attempt}`, {
                file_path: operation.path,
                old_string: oldText,
                new_string: newText,
                ...(previewOnly ? { preview_only: true } : {}),
              });
            let result = await runUpdate(operation.oldText, operation.newText, '');
            {
              const failed = resultDetails(result);
              // The parser always emits newline-terminated oldText/newText, so
              // a hunk anchored at EOF of a file without a trailing newline can
              // never match. Retry with the trailing newline dropped — only
              // when the target file itself ends without one, so mid-file
              // matches are unaffected.
              if (failed.ok === false && failed.error === 'not_found') {
                try {
                  const targetPath = resolveInsideWorkspace(cwd, operation.path);
                  const targetMetadata = await readTextFileWithMetadata(targetPath);
                  if (!targetMetadata.content.endsWith('\n')) {
                    result = await runUpdate(
                      operation.oldText.replace(/\n$/, ''),
                      operation.newText.replace(/\n$/, ''),
                      ':no-trailing-newline'
                    );
                  }
                } catch {
                  // Target unreadable or missing — keep the original failure.
                }
              }
            }
            const details = resultDetails(result);
            if (details.ok === false) {
              if (perFileResults.length === 0) return result;
              perFileResults.push({ ...details, type: 'update', path: operation.path });
              break;
            }
            perFileResults.push({ ...details, type: 'update', path: operation.path });
          }
          const failed = perFileResults.some(result => result.ok === false);
          const patchDiff = perFileResults
            .map(result => result.diff)
            .filter((diff): diff is string => typeof diff === 'string' && diff.length > 0)
            .join('\n');
          const patchDiffDetails = truncateDiffDetail(patchDiff);
          if (failed) {
            return textResult(
              buildMutationResultText({
                action: 'Patch partially failed',
                perFileResults,
                diff: patchDiff,
                snapshotUpdated: false,
              }),
              {
                ok: false,
                error: 'patch_partial_failure',
                perFileResults,
                ...(patchDiff ? { diff: patchDiffDetails.diff } : {}),
                ...(patchDiffDetails.truncated ? { diffTruncated: true } : {}),
              }
            );
          }
          return textResult(
            buildMutationResultText({
              action: previewOnly ? 'Previewed patch' : 'Applied patch',
              fileCount: perFileResults.length,
              perFileResults,
              diff: patchDiff,
              firstChangedLine: perFileResults.find(result => result.firstChangedLine !== undefined)
                ?.firstChangedLine,
              preview: previewOnly,
              snapshotUpdated: false,
            }),
            {
              ok: true,
              ...(previewOnly ? { preview: true } : {}),
              perFileResults,
              diff: patchDiffDetails.diff,
              ...(patchDiffDetails.truncated ? { diffTruncated: true } : {}),
              firstChangedLine: perFileResults.find(result => result.firstChangedLine !== undefined)
                ?.firstChangedLine,
            }
          );
        } catch (err) {
          return errorResult('patch_failed', err instanceof Error ? err.message : String(err));
        }
      }
      const requested = args.file_path;
      if (typeof requested !== 'string' || !requested.trim()) {
        return errorResult('missing_path', 'Edit requires file_path');
      }
      const batchEditsResult = parseBatchEdits(args.edits);
      if (batchEditsResult?.ok === false) {
        return errorResult(
          batchEditsResult.code,
          batchEditsResult.message,
          batchEditsResult.details ?? {}
        );
      }
      const batchEdits = batchEditsResult?.ok === true ? batchEditsResult.edits : undefined;
      const hashlineOperation = parseHashlineOperation(args.hashline_operation);
      const hashlineLine =
        hashlineOperation?.hash ??
        (typeof args.hashline_line === 'string' ? args.hashline_line.trim() : '');
      const isHashlineEdit = Boolean(hashlineLine);
      if (batchEdits && isHashlineEdit) {
        return errorResult(
          'invalid_edit_mode',
          'Edit cannot combine edits with hashline_operation/hashline_line'
        );
      }
      if (
        !isHashlineEdit &&
        !batchEdits &&
        (typeof args.old_string !== 'string' || typeof args.new_string !== 'string')
      ) {
        return errorResult('missing_strings', 'Edit requires old_string and new_string');
      }
      if (!isHashlineEdit && !batchEdits && args.old_string === args.new_string) {
        return errorResult('no_op', 'old_string and new_string are identical');
      }
      if (!batchEdits && typeof args.new_string !== 'string') {
        return errorResult('missing_strings', 'Edit requires new_string');
      }
      const newString = typeof args.new_string === 'string' ? args.new_string : '';
      const oldString = typeof args.old_string === 'string' ? args.old_string : '';
      const replaceAll = args.replace_all === true;
      let filePath: string;
      try {
        filePath = resolveInsideWorkspace(cwd, requested);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const replacementGuard = batchEdits
        ? batchEdits
            .map((edit, index) => ({
              index,
              guard: validateMutationContent(filePath, edit.newString),
            }))
            .find(entry => entry.guard)
        : { index: undefined, guard: validateMutationContent(filePath, newString) };
      if (replacementGuard?.guard) {
        return errorResult(
          replacementGuard.guard.code,
          replacementGuard.guard.message,
          guardErrorDetails(replacementGuard.guard, {
            path: toWorkspaceRelative(cwd, filePath),
            ...(replacementGuard.index !== undefined ? { editIndex: replacementGuard.index } : {}),
          })
        );
      }
      try {
        return await runWithFileWriteLock(filePath, async () => {
          const relPathForChecks = toWorkspaceRelative(cwd, filePath);
          const targetResult = await resolveWritePath(cwd, filePath, relPathForChecks);
          if (!targetResult.ok) return targetResult.result;
          const writePath = targetResult.writePath;
          const fileStat = await stat(filePath); // follows the symlink to its target
          if (!fileStat.isFile()) {
            return errorResult('not_a_file', `Path is not a file: ${relPathForChecks}`);
          }
          if (fileStat.size > MAX_EDIT_FILE_BYTES) {
            return errorResult(
              'file_too_large',
              `File is too large to edit safely: ${relPathForChecks}`,
              {
                path: relPathForChecks,
                size: fileStat.size,
                maxSize: MAX_EDIT_FILE_BYTES,
              }
            );
          }
          if (path.extname(filePath).toLowerCase() === '.ipynb') {
            return errorResult(
              'unsupported_notebook_edit',
              'Jupyter notebooks require a notebook-aware edit tool.',
              {
                path: relPathForChecks,
              }
            );
          }
          const originalMetadata = await readTextFileWithMetadata(filePath);
          const original = originalMetadata.content;
          const generatedMarker = findAutoGeneratedMarker(filePath, original);
          if (generatedMarker) {
            const relPath = toWorkspaceRelative(cwd, filePath);
            return errorResult(
              'auto_generated_file',
              buildAutoGeneratedMessage(relPath, generatedMarker),
              { path: relPath }
            );
          }
          // Hashline edits tolerate out-of-band drift: the content-hash anchor —
          // not the file-level tag or mtime — decides whether the edit is safe.
          let hashlineTagDrift = false;
          if (isHashlineEdit && typeof args.hashline_tag === 'string' && args.hashline_tag.trim()) {
            hashlineTagDrift = hashlineTag(original) !== args.hashline_tag.trim();
          }
          const readEntry = options?.readFileState?.get(filePath);
          const readCheck = isHashlineEdit
            ? options?.readFileState?.assertEditableHashline(filePath)
            : options?.readFileState?.assertEditable(filePath, original);
          let rebased = false;
          if (readCheck && !readCheck.ok) {
            const relPath = toWorkspaceRelative(cwd, filePath);
            if (!isHashlineEdit && readCheck.code === 'file_modified_since_read') {
              rebased = true;
            } else {
              return errorResult(
                readCheck.code,
                readCheck.message,
                readGuardFailureDetails({
                  code: readCheck.code,
                  relPath,
                  currentContent: original,
                  readEntry,
                })
              );
            }
          }
          const staleRebaseFailure = (
            code: string,
            message: string,
            details: Record<string, unknown> = {}
          ): ReturnType<typeof errorResult> => {
            const relPath = toWorkspaceRelative(cwd, filePath);
            if (!rebased) return errorResult(code, message, details);
            return errorResult(
              'file_modified_since_read',
              'File has changed since it was read and the requested edit could not be safely rebased. Read it again before editing.',
              readGuardFailureDetails({
                code: 'file_modified_since_read',
                relPath,
                currentContent: original,
                readEntry,
                extra: {
                  rebaseFailed: true,
                  rebaseError: code,
                  ...details,
                },
              })
            );
          };
          if (rebased) {
            const rebaseAnchorCheck = assertRebaseAnchorsWereRead(
              readEntry?.content,
              batchEdits ?? [{ oldString, newString, replaceAll }]
            );
            if (!rebaseAnchorCheck.ok) {
              return staleRebaseFailure(
                rebaseAnchorCheck.code,
                rebaseAnchorCheck.message,
                rebaseAnchorCheck.details
              );
            }
          }
          if (batchEdits) {
            const relPath = toWorkspaceRelative(cwd, filePath);
            let updated = original;
            let totalReplaced = 0;
            const appliedEdits: Array<{ index: number; replaced: number; replaceAll: boolean }> =
              [];
            for (let index = 0; index < batchEdits.length; index += 1) {
              const edit = batchEdits[index];
              const actual = findActualString(updated, edit.oldString);
              if (actual === null) {
                const ws = findWhitespaceMatch(updated, edit.oldString, edit.newString);
                if (ws.ok) {
                  updated =
                    updated.slice(0, ws.match.start) +
                    ws.match.adjustedNewString +
                    updated.slice(ws.match.end);
                  totalReplaced += 1;
                  appliedEdits.push({ index, replaced: 1, replaceAll: edit.replaceAll });
                  continue;
                }
                if (ws.reason === 'ambiguous') {
                  return staleRebaseFailure(
                    'not_unique',
                    `edits[${index}].old_string matches ${ws.count} locations after whitespace-normalization; add more surrounding context`,
                    { path: relPath, editIndex: index, occurrences: ws.count }
                  );
                }
                const attempts =
                  options?.noopGuard?.record(
                    filePath,
                    `batch_not_found:${index}:${hashlineForLine(edit.oldString)}`
                  ) ?? 0;
                if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                  return errorResult(
                    'edit_loop_detected',
                    `This batch edit has failed ${attempts} times — edits[${index}].old_string does not exist in ${relPath}. ` +
                      'Read the file again to see its current content before retrying.',
                    { path: relPath, editIndex: index, attempts }
                  );
                }
                return staleRebaseFailure(
                  'not_found',
                  `edits[${index}].old_string not found in file`,
                  { path: relPath, editIndex: index }
                );
              }
              const occurrences = countOccurrences(updated, actual);
              if (!edit.replaceAll && occurrences > 1) {
                return staleRebaseFailure(
                  'not_unique',
                  `edits[${index}].old_string appears ${occurrences} times; pass replace_all:true or add more context`,
                  {
                    path: relPath,
                    editIndex: index,
                    occurrences,
                  }
                );
              }
              const replaced = edit.replaceAll ? occurrences : 1;
              updated = applyEdit(updated, actual, edit.newString, edit.replaceAll);
              totalReplaced += replaced;
              appliedEdits.push({ index, replaced, replaceAll: edit.replaceAll });
            }

            if (updated === original) {
              const attempts =
                options?.noopGuard?.record(filePath, `batch_noop:${batchEdits.length}`) ?? 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This batch edit leaves ${relPath} unchanged and has been repeated ${attempts} times. ` +
                    'Read the file — the change may already be in place.',
                  { path: relPath, attempts }
                );
              }
              return errorResult('no_op', 'Batch edits leave the file unchanged', {
                path: relPath,
              });
            }

            const updatedGuard = validateUpdatedContent(filePath, updated, { path: relPath });
            if (!updatedGuard.ok) return updatedGuard.result;
            const diff = buildFileDiff(relPath, original, updated);
            const state = buildMutationStateDescriptor({
              relPath,
              originalContent: original,
              updatedContent: updated,
              diff,
              snapshotUpdated: args.preview_only !== true,
              readSnapshotContent: rebased ? readEntry?.content : undefined,
              rebased,
            });
            const detailsBase = buildMutationDetailsBase({
              path: relPath,
              diff,
              extra: {
                replaced: totalReplaced,
                editCount: batchEdits.length,
                edits: appliedEdits,
                state,
                ...(rebased ? { rebased: true } : {}),
              },
            });
            if (args.preview_only === true) {
              return textResult(
                buildMutationResultText({
                  action: 'Previewed edit',
                  path: relPath,
                  replaced: totalReplaced,
                  editCount: batchEdits.length,
                  diff: diff.diff,
                  firstChangedLine: diff.firstChangedLine,
                  lineChanges: diff.lineChanges,
                  preview: true,
                  snapshotUpdated: false,
                  state,
                  rebased,
                }),
                {
                  ...detailsBase,
                  preview: true,
                }
              );
            }

            const backup = await recordFileBackup(relPath, original, writePath);
            await writeTextFileAtomic(
              writePath,
              applyLineEndingStyle(updated, lineEndingFor(original)),
              originalMetadata
            );
            await options?.readFileState?.recordWrite(filePath, updated);
            options?.noopGuard?.clear(filePath);
            const lifecycleInput = {
              operation: 'edit',
              type: 'update',
              path: relPath,
              absolutePath: filePath,
              originalContent: original,
              updatedContent: updated,
              diff: diff.diff,
              ...(diff.firstChangedLine !== undefined
                ? { firstChangedLine: diff.firstChangedLine }
                : {}),
            } as const;
            const lifecycle = mergeWriteLifecycleResults(
              await runWriteLifecycle(options?.writeLifecycle, lifecycleInput),
              options?.diagnosticsMode === 'deferred'
                ? scheduleDeferredDiagnostics(options?.diagnosticsProvider, lifecycleInput)
                : await runDiagnosticsProvider(options?.diagnosticsProvider, lifecycleInput)
            );
            return textResult(
              buildMutationResultText({
                action: 'Edited',
                path: relPath,
                replaced: totalReplaced,
                editCount: batchEdits.length,
                diff: diff.diff,
                firstChangedLine: diff.firstChangedLine,
                lineChanges: diff.lineChanges,
                state,
                rebased,
              }),
              {
                ...detailsBase,
                backup,
                ...(lifecycle ? { lifecycle } : {}),
              }
            );
          }

          const actual = isHashlineEdit ? null : findActualString(original, oldString);
          if (isHashlineEdit) {
            // The snapshot (file as the model last saw it) disambiguates duplicate lines.
            const snapshot = options?.readFileState?.get(filePath)?.content;
            const updated = replaceHashlineLine(original, hashlineLine, newString, snapshot);
            const relPath = toWorkspaceRelative(cwd, filePath);
            if (updated === undefined) {
              const attempts =
                options?.noopGuard?.record(filePath, `hashline_mismatch:${hashlineLine}`) ?? 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This hashline edit has failed ${attempts} times — the anchored line no longer exists in ${relPath}. ` +
                    'Read the file again with hashline:true to get fresh anchors.',
                  { path: relPath, attempts }
                );
              }
              return errorResult(
                'hashline_mismatch',
                'hashline_line was not found in the current file' +
                  (hashlineTagDrift ? ' (the file has changed since it was read)' : ''),
                {
                  path: relPath,
                  retryable: true,
                  suggestedAction: 'refresh_hashline',
                  suggestion: 'Read the file again with hashline:true before editing.',
                  state: buildFileStateErrorDescriptor({
                    relPath,
                    currentContent: original,
                    readContent: readEntry?.content,
                    hasFullContent: readEntry?.hasFullContent,
                    partialView: readEntry?.isPartialView,
                  }),
                }
              );
            }
            const updatedGuard = validateUpdatedContent(filePath, updated, { path: relPath });
            if (!updatedGuard.ok) return updatedGuard.result;
            const diff = buildFileDiff(relPath, original, updated);
            const state = buildMutationStateDescriptor({
              relPath,
              originalContent: original,
              updatedContent: updated,
              diff,
              snapshotUpdated: args.preview_only !== true,
              readSnapshotContent: hashlineTagDrift ? readEntry?.content : undefined,
              rebased: hashlineTagDrift,
            });
            const hashlineDetailsBase = buildMutationDetailsBase({
              path: relPath,
              diff,
              extra: {
                replaced: 1,
                state,
                ...(hashlineTagDrift ? { rebased: true } : {}),
              },
            });
            if (args.preview_only === true) {
              return textResult(
                buildMutationResultText({
                  action: 'Previewed edit',
                  path: relPath,
                  replaced: 1,
                  diff: diff.diff,
                  firstChangedLine: diff.firstChangedLine,
                  lineChanges: diff.lineChanges,
                  preview: true,
                  snapshotUpdated: false,
                  state,
                  rebased: hashlineTagDrift,
                }),
                {
                  ...hashlineDetailsBase,
                  preview: true,
                  hashline: {
                    tag: hashlineTag(original),
                    ...(hashlineTagDrift ? { tagDrift: true } : {}),
                  },
                }
              );
            }
            if (updated === original) {
              const attempts = options?.noopGuard?.record(filePath, `noop:${hashlineLine}`) ?? 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This edit leaves ${relPath} unchanged and has been repeated ${attempts} times. ` +
                    'Read the file — the change may already be in place.',
                  { path: relPath, attempts }
                );
              }
            } else {
              options?.noopGuard?.clear(filePath);
            }
            const backup = await recordFileBackup(relPath, original, writePath);
            await writeTextFileAtomic(
              writePath,
              applyLineEndingStyle(updated, lineEndingFor(original)),
              originalMetadata
            );
            await options?.readFileState?.recordWrite(filePath, updated);
            return textResult(
              buildMutationResultText({
                action: 'Edited',
                path: relPath,
                replaced: 1,
                diff: diff.diff,
                firstChangedLine: diff.firstChangedLine,
                lineChanges: diff.lineChanges,
                state,
                rebased: hashlineTagDrift,
              }),
              {
                ...hashlineDetailsBase,
                hashline: {
                  tag: hashlineTag(updated),
                  ...(hashlineTagDrift ? { tagDrift: true } : {}),
                },
                backup,
              }
            );
          }
          let updated: string;
          let replaced: number;
          let matchStrategy: 'exact' | 'quote' | 'whitespace';
          if (actual === null) {
            const relPathNF = toWorkspaceRelative(cwd, filePath);
            const ws = findWhitespaceMatch(original, oldString, newString);
            if (ws.ok) {
              updated =
                original.slice(0, ws.match.start) +
                ws.match.adjustedNewString +
                original.slice(ws.match.end);
              replaced = 1;
              matchStrategy = 'whitespace';
            } else if (ws.reason === 'ambiguous') {
              return staleRebaseFailure(
                'not_unique',
                `old_string matches ${ws.count} locations after whitespace-normalization; add more surrounding context`,
                { path: relPathNF, occurrences: ws.count }
              );
            } else {
              const attempts =
                options?.noopGuard?.record(filePath, `not_found:${hashlineForLine(oldString)}`) ??
                0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This exact edit has failed ${attempts} times — old_string does not exist in ${relPathNF}. ` +
                    'Read the file again to see its current content before retrying.',
                  { path: relPathNF, attempts }
                );
              }
              return staleRebaseFailure('not_found', 'old_string not found in file', {
                path: relPathNF,
              });
            }
          } else {
            const occurrences = countOccurrences(original, actual);
            if (!replaceAll && occurrences > 1) {
              return staleRebaseFailure(
                'not_unique',
                `old_string appears ${occurrences} times; pass replace_all:true or add more context`,
                {
                  path: toWorkspaceRelative(cwd, filePath),
                  occurrences,
                }
              );
            }
            updated = applyEdit(original, actual, newString, replaceAll);
            replaced = replaceAll ? occurrences : 1;
            matchStrategy = actual === oldString ? 'exact' : 'quote';
          }
          const relPath = toWorkspaceRelative(cwd, filePath);
          const updatedGuard = validateUpdatedContent(filePath, updated, { path: relPath });
          if (!updatedGuard.ok) return updatedGuard.result;
          const diff = buildFileDiff(relPath, original, updated);
          const state = buildMutationStateDescriptor({
            relPath,
            originalContent: original,
            updatedContent: updated,
            diff,
            snapshotUpdated: args.preview_only !== true,
            readSnapshotContent: rebased ? readEntry?.content : undefined,
            rebased,
          });
          const detailsBase = buildMutationDetailsBase({
            path: relPath,
            diff,
            extra: {
              replaced,
              state,
              ...(rebased ? { rebased: true } : {}),
            },
          });
          if (args.preview_only === true) {
            return textResult(
              buildMutationResultText({
                action: 'Previewed edit',
                path: relPath,
                replaced,
                diff: diff.diff,
                firstChangedLine: diff.firstChangedLine,
                lineChanges: diff.lineChanges,
                preview: true,
                snapshotUpdated: false,
                state,
                rebased,
              }),
              {
                ...detailsBase,
                matchStrategy,
                preview: true,
              }
            );
          }
          const backup = await recordFileBackup(relPath, original, writePath);
          await writeTextFileAtomic(
            writePath,
            applyLineEndingStyle(updated, lineEndingFor(original)),
            originalMetadata
          );
          await options?.readFileState?.recordWrite(filePath, updated);
          if (updated !== original) options?.noopGuard?.clear(filePath);
          const lifecycleInput = {
            operation: 'edit',
            type: 'update',
            path: relPath,
            absolutePath: filePath,
            originalContent: original,
            updatedContent: updated,
            diff: diff.diff,
            ...(diff.firstChangedLine !== undefined
              ? { firstChangedLine: diff.firstChangedLine }
              : {}),
          } as const;
          const lifecycle = mergeWriteLifecycleResults(
            await runWriteLifecycle(options?.writeLifecycle, lifecycleInput),
            options?.diagnosticsMode === 'deferred'
              ? scheduleDeferredDiagnostics(options?.diagnosticsProvider, lifecycleInput)
              : await runDiagnosticsProvider(options?.diagnosticsProvider, lifecycleInput)
          );
          return textResult(
            buildMutationResultText({
              action: 'Edited',
              path: relPath,
              replaced,
              diff: diff.diff,
              firstChangedLine: diff.firstChangedLine,
              lineChanges: diff.lineChanges,
              state,
              rebased,
            }),
            {
              ...detailsBase,
              matchStrategy,
              backup,
              ...(lifecycle ? { lifecycle } : {}),
            }
          );
        });
      } catch (err) {
        return errorResult('edit_failed', err instanceof Error ? err.message : String(err), {
          path: String(requested),
        });
      }
    },
  } as unknown as AgentTool;
}
