/**
 * The Write bridge tool: creates or overwrites a workspace file behind the
 * pi runtime's read-state, diff, backup, and write-lifecycle machinery.
 */

import type { AgentTool } from '@earendil-works/pi-agent-core';
import { mkdir, stat } from 'fs/promises';
import * as path from 'path';

import { buildAutoGeneratedMessage, findAutoGeneratedMarker } from '../auto-generated-guard.js';
import { buildFileDiff } from '../diff.js';
import { buildMutationStateDescriptor } from '../file-state.js';
import { recordFileBackup } from '../file-history.js';
import { runWithFileWriteLock } from '../file-write-lock.js';
import {
  applyLineEndingStyle,
  lineEndingFor,
  maybeMarkExecutableForShebang,
  readTextFileWithMetadata,
  writeTextFileAtomic,
} from '../text-io.js';
import { validateMutationContent } from '../write-guards.js';
import {
  mergeWriteLifecycleResults,
  runDiagnosticsProvider,
  runWriteLifecycle,
  scheduleDeferredDiagnostics,
} from '../write-lifecycle.js';
import { resolveInsideWorkspace, toWorkspaceRelative } from '../workspace-paths.js';
import { buildBudgetedDiffDetails, buildMutationResultText } from './mutation-details.js';
import {
  errorResult,
  guardErrorDetails,
  readGuardFailureDetails,
  resolveWritePath,
  textResult,
  toolParams,
  type FileMutationToolOptions,
} from './shared.js';

export function createWriteBridgeTool(cwd: string, options?: FileMutationToolOptions): AgentTool {
  return {
    name: 'Write',
    label: 'Write',
    description:
      'Write (create or overwrite) a file in the workspace. Creates parent directories as needed. Successful results include a model-visible diff and update the internal file snapshot, so do not call Read again only to verify the write.',
    parameters: {
      type: 'object',
      properties: {
        file_path: { type: 'string', description: 'Workspace-relative path of the file to write' },
        content: { type: 'string', description: 'Full file contents' },
      },
      required: ['file_path', 'content'],
    },
    execute: async (toolCallId: string, params: unknown) => {
      const args = toolParams(toolCallId, params);
      const requested = args.file_path;
      if (typeof requested !== 'string' || !requested.trim()) {
        return errorResult('missing_path', 'Write requires file_path');
      }
      if (typeof args.content !== 'string') {
        return errorResult('missing_content', 'Write requires string content');
      }
      const content = args.content;
      let filePath: string;
      try {
        filePath = resolveInsideWorkspace(cwd, requested);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const contentGuard = validateMutationContent(filePath, content);
      if (contentGuard) {
        return errorResult(
          contentGuard.code,
          contentGuard.message,
          guardErrorDetails(contentGuard, {
            path: toWorkspaceRelative(cwd, filePath),
          })
        );
      }
      const filenameMarker = findAutoGeneratedMarker(filePath, null);
      if (filenameMarker) {
        const relPath = toWorkspaceRelative(cwd, filePath);
        return errorResult(
          'auto_generated_file',
          buildAutoGeneratedMessage(relPath, filenameMarker),
          { path: relPath }
        );
      }
      try {
        return await runWithFileWriteLock(filePath, async () => {
          const relPathForSymlink = toWorkspaceRelative(cwd, filePath);
          const targetResult = await resolveWritePath(cwd, filePath, relPathForSymlink);
          if (!targetResult.ok) return targetResult.result;
          const writePath = targetResult.writePath;
          let existed = false;
          let originalContent: string | null = null;
          try {
            const targetStat = await stat(writePath);
            if (!targetStat.isFile()) {
              return errorResult('not_a_file', `Path is not a file: ${relPathForSymlink}`, {
                path: relPathForSymlink,
              });
            }
            existed = true;
          } catch (err) {
            const code = (err as NodeJS.ErrnoException)?.code;
            if (code !== 'ENOENT') throw err;
            // new file
          }
          let originalMetadata: Awaited<ReturnType<typeof readTextFileWithMetadata>> | undefined;
          if (existed) {
            originalMetadata = await readTextFileWithMetadata(writePath);
            originalContent = originalMetadata.content;
            const generatedMarker = findAutoGeneratedMarker(filePath, originalContent);
            if (generatedMarker) {
              const relPath = toWorkspaceRelative(cwd, filePath);
              return errorResult(
                'auto_generated_file',
                buildAutoGeneratedMessage(relPath, generatedMarker),
                { path: relPath }
              );
            }
            const readCheck = await options?.readFileState?.assertSafeToWrite(
              filePath,
              originalContent
            );
            if (readCheck && !readCheck.ok) {
              const relPath = toWorkspaceRelative(cwd, filePath);
              return errorResult(
                readCheck.code,
                readCheck.message,
                readGuardFailureDetails({
                  code: readCheck.code,
                  relPath,
                  currentContent: originalContent,
                  readEntry: options?.readFileState?.get(filePath),
                })
              );
            }
          }
          await mkdir(path.dirname(writePath), { recursive: true });
          const relPath = toWorkspaceRelative(cwd, filePath);
          const backup =
            originalContent !== null
              ? await recordFileBackup(relPath, originalContent, writePath)
              : undefined;
          const updatedContentForDisk =
            originalContent !== null
              ? applyLineEndingStyle(content, lineEndingFor(originalContent))
              : content;
          await writeTextFileAtomic(writePath, updatedContentForDisk, originalMetadata);
          const madeExecutable = await maybeMarkExecutableForShebang(writePath, content);
          await options?.readFileState?.recordWrite(filePath, content);
          options?.noopGuard?.clear(filePath);
          const diff =
            originalContent !== null
              ? buildFileDiff(relPath, originalContent, content)
              : buildFileDiff(relPath, '', content);
          const diffDetails = buildBudgetedDiffDetails(diff);
          const state = buildMutationStateDescriptor({
            relPath,
            originalContent,
            updatedContent: content,
            diff,
            snapshotUpdated: true,
          });
          const writeType = existed ? 'update' : 'create';
          const lifecycleInput = {
            operation: 'write',
            type: writeType,
            path: relPath,
            absolutePath: filePath,
            originalContent,
            updatedContent: content,
            diff: diff.diff,
            ...(diff.firstChangedLine !== undefined
              ? { firstChangedLine: diff.firstChangedLine }
              : {}),
          } as const;
          const lifecycle = mergeWriteLifecycleResults(
            await runWriteLifecycle(options?.writeLifecycle, lifecycleInput),
            options?.diagnosticsMode === 'deferred'
              ? scheduleDeferredDiagnostics(options?.diagnosticsProvider, lifecycleInput)
              : await runDiagnosticsProvider(options?.diagnosticsProvider, lifecycleInput)
          );
          const details = {
            ok: true,
            type: writeType,
            path: relPath,
            diff: diffDetails.diff,
            firstChangedLine: diff.firstChangedLine,
            structuredPatch: diffDetails.structuredPatch,
            lineChanges: diff.lineChanges,
            state,
            ...(diffDetails.diffTruncated ? { diffTruncated: true } : {}),
            ...(diffDetails.structuredPatchTruncated ? { structuredPatchTruncated: true } : {}),
            ...(backup ? { backup } : {}),
            ...(madeExecutable ? { madeExecutable: true } : {}),
            ...(lifecycle ? { lifecycle } : {}),
          };
          return textResult(
            buildMutationResultText({
              action: 'Wrote',
              path: relPath,
              type: writeType,
              diff: diff.diff,
              firstChangedLine: diff.firstChangedLine,
              lineChanges: diff.lineChanges,
              state,
            }),
            details
          );
        });
      } catch (err) {
        return errorResult('write_failed', err instanceof Error ? err.message : String(err), {
          path: String(requested),
        });
      }
    },
  } as unknown as AgentTool;
}
