import { describe, it, expect } from 'vitest';
import { findAutoGeneratedMarker } from '../auto-generated-guard.js';

describe('findAutoGeneratedMarker', () => {
  describe('filename patterns', () => {
    const generated = [
      'api/v1/service.pb.go',
      'proto/service_pb2.py',
      'proto/service_pb2_grpc.py',
      'pkg/apis/zz_generated.deepcopy.go',
      'db/schema.gen.ts',
      'api.swagger.json',
      'store/store.mock.go',
    ];
    for (const filePath of generated) {
      it(`flags by filename: ${filePath}`, () => {
        expect(findAutoGeneratedMarker(filePath, null)).toBeDefined();
      });
    }

    it('does not flag ordinary filenames', () => {
      expect(findAutoGeneratedMarker('src/generator.ts', null)).toBeUndefined();
      expect(findAutoGeneratedMarker('src/pb-utils.ts', null)).toBeUndefined();
      expect(findAutoGeneratedMarker('docs/generated-docs-guide.md', null)).toBeUndefined();
    });
  });

  describe('header markers', () => {
    it('flags Go protoc header', () => {
      const content =
        '// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\npackage v1\n';
      expect(findAutoGeneratedMarker('service.go', content)).toBeDefined();
    });

    it('flags @generated marker in hash comments', () => {
      const content = '# @generated by tooling\nimport os\n';
      expect(findAutoGeneratedMarker('module.py', content)).toBeDefined();
    });

    it('flags marker after a shebang line', () => {
      const content =
        '#!/usr/bin/env python\n# This file was automatically generated\nprint("hi")\n';
      expect(findAutoGeneratedMarker('script.py', content)).toBeDefined();
    });

    it('flags block-comment markers', () => {
      const content = '/*\n * @generated\n */\nexport const x = 1;\n';
      expect(findAutoGeneratedMarker('module.ts', content)).toBeDefined();
    });

    it('ignores markers outside the header comment', () => {
      const lines = [
        'export function describeGuard() {',
        "  return 'detects @generated headers';",
        '}',
        '',
      ];
      expect(findAutoGeneratedMarker('guard.ts', lines.join('\n'))).toBeUndefined();
    });

    it('ignores prose mentioning generation in normal code comments', () => {
      const content = '// Helpers for the report generator.\nexport const x = 1;\n';
      expect(findAutoGeneratedMarker('helpers.ts', content)).toBeUndefined();
    });

    it('does not scan files without a known comment style', () => {
      const content = '@generated\nsome text\n';
      expect(findAutoGeneratedMarker('notes.md', content)).toBeUndefined();
    });

    it('handles null content (file does not exist yet)', () => {
      expect(findAutoGeneratedMarker('new-file.ts', null)).toBeUndefined();
    });
  });
});
