import { describe, it, expect } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync, existsSync, readFileSync } from 'fs';
import { tmpdir } from 'os';
import path from 'path';
import { buildTools } from '../tool-bridge.js';

function makeWorkspace(): string {
  return mkdtempSync(path.join(tmpdir(), 'zc-guards-'));
}

function getTools(dir: string, options: Record<string, unknown> = {}): Record<string, any> {
  const tools = buildTools(dir, { enabled: ['Read', 'Edit', 'Write', 'Bash'], ...options });
  return Object.fromEntries(tools.map(t => [t.name, t]));
}

function getTool(dir: string, name: string, options: Record<string, unknown> = {}): any {
  return getTools(dir, options)[name];
}

const GENERATED_GO =
  '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage v1\n\nvar Name = "old"\n';

describe('auto-generated file guard (Edit/Write integration)', () => {
  it('Edit refuses to modify a file with a generator header', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'service.go'), GENERATED_GO);
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'service.go' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'service.go',
      old_string: 'var Name = "old"',
      new_string: 'var Name = "new"',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('auto_generated_file');
    expect(res.content[0].text).toContain('regenerate');
  });

  it('Write refuses to overwrite a file with a generator header', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'service.go'), GENERATED_GO);
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'service.go' });
    const res = await tools.Write.execute('w1', {
      file_path: 'service.go',
      content: 'package v1\n',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('auto_generated_file');
  });

  it('Write refuses to create a new file matching a generated filename pattern', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Write').execute('w1', {
      file_path: 'api/service.pb.go',
      content: 'package v1\n',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('auto_generated_file');
  });

  it('Edit still works on hand-written files', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'main.go'), 'package main\n\nvar Name = "old"\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'main.go' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'main.go',
      old_string: 'var Name = "old"',
      new_string: 'var Name = "new"',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
  });
});

describe('critical Bash command guard (integration)', () => {
  // Matches the fetch-then-execute pattern but is harmless: curl fails on a
  // closed local port, bash receives empty stdin, the trailing marker proves execution.
  const CRITICAL_BUT_HARMLESS = 'curl -s --max-time 1 http://127.0.0.1:9/ | bash; touch ran.marker';

  it('blocks a critical command when no permission channel is available', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Bash').execute('b1', { command: CRITICAL_BUT_HARMLESS });
    const executed = existsSync(path.join(dir, 'ran.marker'));
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('critical_command_blocked');
    expect(executed).toBe(false);
  });

  it('blocks when the user denies the escalation', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Bash', {
      permissionCallback: async () => ({ behavior: 'deny', message: 'no' }),
    }).execute('b1', { command: CRITICAL_BUT_HARMLESS });
    const executed = existsSync(path.join(dir, 'ran.marker'));
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('critical_command_blocked');
    expect(executed).toBe(false);
  });

  it('runs the command when the user approves the escalation', async () => {
    const dir = makeWorkspace();

    let request: any;
    const res = await getTool(dir, 'Bash', {
      permissionCallback: async (req: any) => {
        request = req;
        return { behavior: 'allow' };
      },
    }).execute('b1', { command: CRITICAL_BUT_HARMLESS });
    const executed = existsSync(path.join(dir, 'ran.marker'));
    rmSync(dir, { recursive: true, force: true });
    expect(request.toolName).toBe('CriticalBashCommand');
    expect(request.toolInput.command).toBe(CRITICAL_BUT_HARMLESS);
    expect(res.details.exitCode).toBe(0);
    expect(executed).toBe(true);
  });

  it('guards the background path before any task is created', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Bash').execute('b1', {
      command: CRITICAL_BUT_HARMLESS,
      run_in_background: true,
    });
    rmSync(dir, { recursive: true, force: true });
    // Blocked by the guard, not by the missing db context of the background path.
    expect(res.details.error).toBe('critical_command_blocked');
  });

  it('does not prompt for ordinary commands', async () => {
    const dir = makeWorkspace();
    let asked = 0;
    const res = await getTool(dir, 'Bash', {
      permissionCallback: async () => {
        asked++;
        return { behavior: 'allow' };
      },
    }).execute('b1', { command: 'echo hello' });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
    expect(asked).toBe(0);
  });
});

describe('edit-after-summary / edit-after-range guard (Option B)', () => {
  function bigTs(): string {
    const blocks: string[] = [];
    for (let f = 0; f < 30; f++) {
      blocks.push(`function fn${f}() {`);
      for (let b = 0; b < 8; b++) blocks.push(`  const v${f}_${b} = ${b};`);
      blocks.push('}');
    }
    return blocks.join('\n');
  }

  it('Edit succeeds after a structural summary read (no full re-read)', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'big.ts'), bigTs());
    const tools = getTools(dir);
    const read = await tools.Read.execute('r1', { path: 'big.ts' });
    expect(read.details.format).toBe('outline');
    const res = await tools.Edit.execute('e1', {
      file_path: 'big.ts',
      old_string: 'const v0_0 = 0;',
      new_string: 'const v0_0 = 42;',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
  });

  it('Edit succeeds after a ranged read (no full re-read)', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'main.ts'), 'const a = "old";\nconst b = 2;\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'main.ts', offset: 1, limit: 1 });
    const res = await tools.Edit.execute('e1', {
      file_path: 'main.ts',
      old_string: 'const a = "old";',
      new_string: 'const a = "new";',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
  });

  it('Write is still blocked after only a summary read', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'big.ts'), bigTs());
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'big.ts' });
    const res = await tools.Write.execute('w1', { file_path: 'big.ts', content: 'package\n' });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: false, error: 'partial_read' });
  });

  it('Edit is blocked when the file changed since the read', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'm.ts'), 'const a = "old";\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'm.ts' });
    writeFileSync(path.join(dir, 'm.ts'), 'const a = "drifted";\n');
    const res = await tools.Edit.execute('e1', {
      file_path: 'm.ts',
      old_string: 'const a = "drifted";',
      new_string: 'const a = "new";',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: false, error: 'file_modified_since_read' });
  });
});

describe('decoupled mutation caps', () => {
  it('edits a file larger than the old 512KB cap (now allowed under the 10MB Edit cap)', async () => {
    const dir = makeWorkspace();
    const body = Array.from({ length: 10_000 }, (_, i) => `const v${i} = ${i};`).join('\n');
    writeFileSync(path.join(dir, 'big.ts'), `const target = 1;\n${body}\n`);
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'big.ts' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'big.ts',
      old_string: 'const target = 1;',
      new_string: 'const target = 2;',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
  });

  it('rejects Write content larger than the 2MB Write cap', async () => {
    const dir = makeWorkspace();
    const tools = getTools(dir);
    const content = 'x'.repeat(2 * 1024 * 1024 + 1);
    const res = await tools.Write.execute('w1', { file_path: 'big.txt', content });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: false, error: 'content_too_large' });
  });

  it('accepts Write content under the 2MB cap', async () => {
    const dir = makeWorkspace();
    const tools = getTools(dir);
    const content = 'x'.repeat(1024 * 1024);
    const res = await tools.Write.execute('w1', { file_path: 'ok.txt', content });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
  });
});

describe('Edit whitespace-safe matching', () => {
  it('edits a CRLF file with a multi-line LF old_string', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'crlf.ts'), 'const a = 1;\r\nconst b = 2;\r\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'crlf.ts' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'crlf.ts',
      old_string: 'const a = 1;\nconst b = 2;', // LF; the file is CRLF -> exact fails -> whitespace
      new_string: 'const a = 1;\nconst b = 42;',
    });
    const after = readFileSync(path.join(dir, 'crlf.ts'), 'utf8');
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: true, matchStrategy: 'whitespace' });
    expect(after).toBe('const a = 1;\r\nconst b = 42;\r\n'); // CRLF preserved
  });

  it('edits a multi-line block with wrong indentation and re-indents the replacement', async () => {
    const dir = makeWorkspace();
    writeFileSync(
      path.join(dir, 'f.ts'),
      'function f() {\n    const a = 1;\n    const b = 2;\n}\n'
    );
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'f.ts' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'f.ts',
      old_string: '  const a = 1;\n  const b = 2;', // 2-space; file is 4-space -> exact fails -> whitespace
      new_string: '  const a = 1;\n  const c = 3;',
    });
    const after = readFileSync(path.join(dir, 'f.ts'), 'utf8');
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: true, matchStrategy: 'whitespace' });
    expect(after).toBe('function f() {\n    const a = 1;\n    const c = 3;\n}\n'); // re-indented to 4 spaces
  });

  it('sub-line edits still work via exact match (whitespace matcher not consulted)', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'f.ts'), 'const x = getName();\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'f.ts' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'f.ts',
      old_string: 'getName',
      new_string: 'getFullName',
    });
    const after = readFileSync(path.join(dir, 'f.ts'), 'utf8');
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: true, matchStrategy: 'exact' });
    expect(after).toBe('const x = getFullName();\n');
  });

  it('reports not_unique when the match is ambiguous', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'f.ts'), 'x = 1;\ny = 2;\nx = 1;\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'f.ts' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'f.ts',
      old_string: 'x = 1;',
      new_string: 'x = 9;',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: false, error: 'not_unique' });
  });

  it('exact matches report matchStrategy exact', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'f.ts'), 'const a = 1;\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'f.ts' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'f.ts',
      old_string: 'const a = 1;',
      new_string: 'const a = 2;',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details).toMatchObject({ ok: true, matchStrategy: 'exact' });
  });
});
