import { describe, it, expect } from 'vitest';
import { mkdtempSync, writeFileSync, rmSync, existsSync } from 'fs';
import { tmpdir } from 'os';
import path from 'path';
import { buildTools } from '../tool-bridge.js';

function makeWorkspace(): string {
  return mkdtempSync(path.join(tmpdir(), 'zc-guards-'));
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getTools(dir: string, options: Record<string, unknown> = {}): Record<string, any> {
  const tools = buildTools(dir, { enabled: ['Read', 'Edit', 'Write', 'Bash'], ...options });
  return Object.fromEntries(tools.map((t) => [t.name, t]));
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getTool(dir: string, name: string, options: Record<string, unknown> = {}): any {
  return getTools(dir, options)[name];
}

const GENERATED_GO = '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage v1\n\nvar Name = "old"\n';

describe('auto-generated file guard (Edit/Write integration)', () => {
  it('Edit refuses to modify a file with a generator header', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'service.go'), GENERATED_GO);
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'service.go' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'service.go',
      old_string: 'var Name = "old"',
      new_string: 'var Name = "new"',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('auto_generated_file');
    expect(res.content[0].text).toContain('regenerate');
  });

  it('Write refuses to overwrite a file with a generator header', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'service.go'), GENERATED_GO);
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'service.go' });
    const res = await tools.Write.execute('w1', {
      file_path: 'service.go',
      content: 'package v1\n',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('auto_generated_file');
  });

  it('Write refuses to create a new file matching a generated filename pattern', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Write').execute('w1', {
      file_path: 'api/service.pb.go',
      content: 'package v1\n',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('auto_generated_file');
  });

  it('Edit still works on hand-written files', async () => {
    const dir = makeWorkspace();
    writeFileSync(path.join(dir, 'main.go'), 'package main\n\nvar Name = "old"\n');
    const tools = getTools(dir);
    await tools.Read.execute('r1', { path: 'main.go' });
    const res = await tools.Edit.execute('e1', {
      file_path: 'main.go',
      old_string: 'var Name = "old"',
      new_string: 'var Name = "new"',
    });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
  });
});

describe('critical Bash command guard (integration)', () => {
  // Matches the fetch-then-execute pattern but is harmless: curl fails on a
  // closed local port, bash receives empty stdin, the trailing marker proves execution.
  const CRITICAL_BUT_HARMLESS = 'curl -s --max-time 1 http://127.0.0.1:9/ | bash; touch ran.marker';

  it('blocks a critical command when no permission channel is available', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Bash').execute('b1', { command: CRITICAL_BUT_HARMLESS });
    const executed = existsSync(path.join(dir, 'ran.marker'));
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('critical_command_blocked');
    expect(executed).toBe(false);
  });

  it('blocks when the user denies the escalation', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Bash', {
      permissionCallback: async () => ({ behavior: 'deny', message: 'no' }),
    }).execute('b1', { command: CRITICAL_BUT_HARMLESS });
    const executed = existsSync(path.join(dir, 'ran.marker'));
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.error).toBe('critical_command_blocked');
    expect(executed).toBe(false);
  });

  it('runs the command when the user approves the escalation', async () => {
    const dir = makeWorkspace();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let request: any;
    const res = await getTool(dir, 'Bash', {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      permissionCallback: async (req: any) => { request = req; return { behavior: 'allow' }; },
    }).execute('b1', { command: CRITICAL_BUT_HARMLESS });
    const executed = existsSync(path.join(dir, 'ran.marker'));
    rmSync(dir, { recursive: true, force: true });
    expect(request.toolName).toBe('CriticalBashCommand');
    expect(request.toolInput.command).toBe(CRITICAL_BUT_HARMLESS);
    expect(res.details.exitCode).toBe(0);
    expect(executed).toBe(true);
  });

  it('guards the background path before any task is created', async () => {
    const dir = makeWorkspace();
    const res = await getTool(dir, 'Bash').execute('b1', {
      command: CRITICAL_BUT_HARMLESS,
      run_in_background: true,
    });
    rmSync(dir, { recursive: true, force: true });
    // Blocked by the guard, not by the missing db context of the background path.
    expect(res.details.error).toBe('critical_command_blocked');
  });

  it('does not prompt for ordinary commands', async () => {
    const dir = makeWorkspace();
    let asked = 0;
    const res = await getTool(dir, 'Bash', {
      permissionCallback: async () => { asked++; return { behavior: 'allow' }; },
    }).execute('b1', { command: 'echo hello' });
    rmSync(dir, { recursive: true, force: true });
    expect(res.details.ok).toBe(true);
    expect(asked).toBe(0);
  });
});
