// Fetches the manifest icons from the pinned vscode-symbols commit and
// emits src/components/filesymbols/generated/symbols.ts.
// Usage: pnpm --filter @zclaudia/desktop run gen:symbols
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { UPSTREAM_SHA, ICONS, COLOR_MAP } from './manifest.mjs';
import { transformSvg } from './transform.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(__dirname, '../../src/components/filesymbols/generated');
const outFile = path.join(outDir, 'symbols.ts');
const base = `https://raw.githubusercontent.com/miguelsolorio/vscode-symbols/${UPSTREAM_SHA}/src/icons/files`;

const entries = [];
for (const name of ICONS) {
  const res = await fetch(`${base}/${name}.svg`);
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status} fetching ${res.url}`);
  entries.push([name, transformSvg(name, await res.text(), COLOR_MAP)]);
}

const body = entries
  .map(([name, svg]) => `  '${name}': '${svg.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}',`)
  .join('\n');

const header = `// @generated by scripts/symbols/generate.mjs — do not edit by hand.
// Icon artwork from vscode-symbols (https://github.com/miguelsolorio/vscode-symbols)
// commit ${UPSTREAM_SHA}, MIT License © Miguel Solorio.
// Colors are remapped to the --glyph-* theme tokens (scripts/tokens/config.mjs).
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outFile,
  `${header}\nexport const SYMBOLS = {\n${body}\n} as const;\n\nexport type SymbolName = keyof typeof SYMBOLS;\n`
);
console.log(`symbols.ts written: ${entries.length} icons.`);
