import type { AgentTool } from '@earendil-works/pi-agent-core';
import { readFile } from 'fs/promises';

import { buildAutoGeneratedMessage, findAutoGeneratedMarker } from './auto-generated-guard.js';
import { collectAstFiles, findAstMatches, rewriteAstMatches } from './ast-tools.js';
import { buildFileDiff } from './diff.js';
import { recordFileBackup } from './file-history.js';
import { runWithFileWriteLock } from './file-write-lock.js';
import type { NoopEditGuard } from './noop-edit-guard.js';
import type { ReadFileStateStore } from './read-file-state.js';
import {
  applyLineEndingStyle,
  decodeTextBuffer,
  lineEndingFor,
  readTextFileWithMetadata,
  writeTextFileAtomic,
} from './text-io.js';
import {
  agentToolParameters,
  errorResult,
  textResult,
  toolParams,
  truncateText,
} from './tool-common.js';
import { validateMutationContent } from './write-guards.js';
import { resolveInsideWorkspace, toWorkspaceRelative } from './workspace-paths.js';

export interface AstBridgeToolOptions {
  readFileState?: ReadFileStateStore;
  noopGuard?: NoopEditGuard;
}

/** Output budget for the concatenated AstEdit diff (matches tool-common's default). */
const MAX_AST_EDIT_DIFF_CHARS = 80_000;

export function createAstGrepTool(cwd: string): AgentTool {
  return {
    name: 'AstGrep',
    label: 'AstGrep',
    description:
      'Structural code search via AST patterns (ast-grep syntax). Use metavariables like $ARG / $$$ARGS, e.g. "console.log($ARG)" or "function $NAME($$$PARAMS) { $$$BODY }". Matches syntax, not text - immune to whitespace and formatting. Languages: JS/TS/TSX/HTML/CSS.',
    parameters: agentToolParameters({
      type: 'object',
      properties: {
        pattern: { type: 'string', description: 'AST pattern with $METAVAR placeholders' },
        path: {
          type: 'string',
          description: 'File or directory to search (default: workspace root)',
        },
        max_results: { type: 'number', default: 50 },
      },
      required: ['pattern'],
    }),
    execute: async (toolCallId: string, params: unknown) => {
      const args = toolParams(toolCallId, params);
      if (typeof args.pattern !== 'string' || !args.pattern.trim()) {
        return errorResult('missing_pattern', 'AstGrep requires a pattern');
      }
      let searchRoot: string;
      try {
        searchRoot = resolveInsideWorkspace(cwd, args.path);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const maxResults = Math.max(1, Math.min(Number(args.max_results ?? 50) || 50, 200));
      try {
        const files = await collectAstFiles(searchRoot);
        const lines: string[] = [];
        let total = 0;
        let truncated = false;
        for (const file of files) {
          if (total >= maxResults) {
            truncated = true;
            break;
          }
          let content: string;
          try {
            content = decodeTextBuffer(await readFile(file)).content;
          } catch {
            continue;
          }
          const matches = await findAstMatches(content, file, args.pattern);
          const relPath = toWorkspaceRelative(cwd, file);
          for (const match of matches) {
            if (total >= maxResults) {
              truncated = true;
              break;
            }
            total += 1;
            lines.push(`${relPath}:${match.line}: ${match.text.split('\n')[0]}`);
          }
        }
        return textResult(lines.length > 0 ? lines.join('\n') : 'No matches found.', {
          ok: true,
          matches: total,
          truncated,
        });
      } catch (err) {
        return errorResult('ast_grep_failed', err instanceof Error ? err.message : String(err));
      }
    },
  };
}

export function createAstEditTool(cwd: string, options?: AstBridgeToolOptions): AgentTool {
  return {
    name: 'AstEdit',
    label: 'AstEdit',
    description:
      'Structural rewrite via AST patterns (ast-grep syntax). Replaces every match of pattern with rewrite; metavariables ($ARG, $$$ARGS) captured by the pattern are substituted into the rewrite. Set dry_run:true to preview the diff without writing. Languages: JS/TS/TSX/HTML/CSS.',
    parameters: agentToolParameters({
      type: 'object',
      properties: {
        pattern: { type: 'string', description: 'AST pattern with $METAVAR placeholders' },
        rewrite: {
          type: 'string',
          description: 'Replacement template; may reference captured metavariables',
        },
        path: {
          type: 'string',
          description: 'File or directory to rewrite (default: workspace root)',
        },
        dry_run: {
          type: 'boolean',
          default: false,
          description: 'Preview the diff without writing',
        },
      },
      required: ['pattern', 'rewrite'],
    }),
    execute: async (toolCallId: string, params: unknown) => {
      const args = toolParams(toolCallId, params);
      if (
        typeof args.pattern !== 'string' ||
        !args.pattern.trim() ||
        typeof args.rewrite !== 'string'
      ) {
        return errorResult('missing_pattern', 'AstEdit requires pattern and rewrite');
      }
      let searchRoot: string;
      try {
        searchRoot = resolveInsideWorkspace(cwd, args.path);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const previewOnly = args.dry_run === true;
      try {
        const files = await collectAstFiles(searchRoot);
        const perFileResults: Array<Record<string, unknown>> = [];
        const diffEntries: Array<{
          path: string;
          diff: string;
          hunks: number;
          additions: number;
          deletions: number;
        }> = [];
        let totalReplaced = 0;
        let mutatedFiles = 0;
        for (const file of files) {
          let original: Awaited<ReturnType<typeof readTextFileWithMetadata>>;
          try {
            original = await readTextFileWithMetadata(file);
          } catch {
            continue;
          }
          const result = await rewriteAstMatches(
            original.content,
            file,
            args.pattern,
            args.rewrite
          );
          if (!result || result.updated === original.content) continue;
          const relPath = toWorkspaceRelative(cwd, file);
          const generatedMarker = findAutoGeneratedMarker(file, original.content);
          if (generatedMarker) {
            perFileResults.push({
              ok: false,
              error: 'auto_generated_file',
              path: relPath,
              message: buildAutoGeneratedMessage(relPath, generatedMarker),
            });
            continue;
          }
          // Same mutation-content scan Edit/Write/MultiEdit run: the rewritten
          // content must not introduce secrets or unsafe agent settings.
          const contentGuard = validateMutationContent(file, result.updated);
          if (contentGuard) {
            perFileResults.push({
              ok: false,
              error: contentGuard.code,
              path: relPath,
              message: contentGuard.message,
              ...(contentGuard.details ?? {}),
            });
            continue;
          }
          const diff = buildFileDiff(relPath, original.content, result.updated);
          diffEntries.push({
            path: relPath,
            diff: diff.diff,
            hunks: diff.structuredPatch.length,
            additions: diff.lineChanges.additions,
            deletions: diff.lineChanges.deletions,
          });
          if (!previewOnly) {
            let written = false;
            await runWithFileWriteLock(file, async () => {
              // TOCTOU guard: the rewrite was computed from content read before
              // the lock. Re-read inside the lock and refuse to clobber a
              // concurrent change (mirrors Edit's assertSafeToWrite flow).
              const current = await readTextFileWithMetadata(file);
              if (current.content !== original.content) {
                perFileResults.push({
                  ok: false,
                  error: 'file_changed_during_edit',
                  path: relPath,
                  message:
                    'File changed while AstEdit was running; no changes were written. Retry the edit.',
                });
                return;
              }
              const backup = await recordFileBackup(relPath, original.content, file);
              await writeTextFileAtomic(
                file,
                applyLineEndingStyle(result.updated, lineEndingFor(original.content)),
                current
              );
              await options?.readFileState?.recordWrite(file, result.updated);
              options?.noopGuard?.clear(file);
              written = true;
              perFileResults.push({ ok: true, path: relPath, replaced: result.replaced, backup });
            });
            if (written) {
              totalReplaced += result.replaced;
              mutatedFiles += 1;
            }
          } else {
            perFileResults.push({
              ok: true,
              preview: true,
              path: relPath,
              replaced: result.replaced,
            });
            totalReplaced += result.replaced;
            mutatedFiles += 1;
          }
        }
        const failures = perFileResults.filter(entry => entry.ok === false);
        if (totalReplaced === 0) {
          if (failures.length > 0) {
            const first = failures[0];
            return errorResult(String(first.error), String(first.message ?? 'Edit refused'), {
              perFileResults,
            });
          }
          return errorResult('no_matches', 'Pattern did not match anything in the target path.');
        }
        const summary =
          `${previewOnly ? 'Previewed' : 'Applied'} ${totalReplaced} replacement(s) in ${mutatedFiles} file(s).` +
          (failures.length > 0 ? ` ${failures.length} file(s) skipped.` : '');
        // Cap the concatenated diff; past the budget, fall back to a per-file
        // hunk summary so the model still sees what changed where.
        let diffText = diffEntries.map(entry => entry.diff).join('\n');
        let diffTruncated = false;
        if (diffText.length > MAX_AST_EDIT_DIFF_CHARS) {
          diffTruncated = true;
          const perFileSummary = diffEntries
            .map(
              entry =>
                `${entry.path}: ${entry.hunks} hunk(s), +${entry.additions}/-${entry.deletions}`
            )
            .join('\n');
          diffText =
            `${truncateText(diffText, MAX_AST_EDIT_DIFF_CHARS)}\n\n` +
            `[diff truncated: per-file summary for all ${diffEntries.length} file(s)]\n${perFileSummary}`;
        }
        return textResult(`${summary}\n\n${diffText}`, {
          ok: true,
          ...(previewOnly ? { preview: true } : {}),
          replaced: totalReplaced,
          files: perFileResults,
          diff: diffText,
          ...(diffTruncated ? { diffTruncated: true } : {}),
        });
      } catch (err) {
        return errorResult('ast_edit_failed', err instanceof Error ? err.message : String(err));
      }
    },
  };
}
