import type { AgentTool } from '@earendil-works/pi-agent-core';
import { lstat, mkdir, realpath, rename, rm, stat } from 'fs/promises';
import * as path from 'path';

import {
  findActualString,
  countOccurrences,
  applyEdit,
  findWhitespaceMatch,
} from './edit-match.js';
import { buildFileDiff, type FileDiffHunk, type FileDiffResult } from './diff.js';
import type { ReadFileStateEntry, ReadFileStateStore } from './read-file-state.js';
import {
  mergeWriteLifecycleResults,
  runDiagnosticsProvider,
  runWriteLifecycle,
  scheduleDeferredDiagnostics,
  type DiagnosticsMode,
  type WriteDiagnosticsProvider,
  type WriteLifecycleHooks,
} from './write-lifecycle.js';
import {
  applyLineEndingStyle,
  lineEndingFor,
  maybeMarkExecutableForShebang,
  readTextFileWithMetadata,
  writeTextFileAtomic,
} from './text-io.js';
import { MAX_EDIT_FILE_BYTES, validateMutationContent } from './write-guards.js';
import { buildAutoGeneratedMessage, findAutoGeneratedMarker } from './auto-generated-guard.js';
import { recordFileBackup } from './file-history.js';
import { runWithFileWriteLock } from './file-write-lock.js';
import { parseApplyPatch } from './apply-patch.js';
import {
  hashlineForLine,
  hashlineTag,
  parseHashlineOperation,
  replaceHashlineLine,
} from './hashline.js';
import {
  buildFileStateErrorDescriptor,
  buildMutationStateDescriptor,
  type MutationStateDescriptor,
} from './file-state.js';
import { NOOP_EDIT_HARD_LIMIT, type NoopEditGuard } from './noop-edit-guard.js';
import { resolveInsideWorkspace, toWorkspaceRelative } from './workspace-paths.js';

type TextBlock = { type: 'text'; text: string };
type ToolContent = TextBlock[];
type BatchEditInput = { oldString: string; newString: string; replaceAll: boolean };
type FileMutationTool = AgentTool;
type FileMutationToolResult = Awaited<ReturnType<FileMutationTool['execute']>>;
type FileMutationToolUpdate = Parameters<FileMutationTool['execute']>[3];
type MutationDetails = Record<string, unknown>;

const MODEL_VISIBLE_DIFF_MAX_CHARS = 12_000;
const DETAILS_DIFF_MAX_CHARS = 80_000;
const DETAILS_STRUCTURED_PATCH_MAX_LINES = 400;

export interface FileMutationToolOptions {
  readFileState?: ReadFileStateStore;
  writeLifecycle?: WriteLifecycleHooks;
  diagnosticsProvider?: WriteDiagnosticsProvider;
  diagnosticsMode?: DiagnosticsMode;
  /** Shared per-run guard against repeated identical failed/no-op edits. */
  noopGuard?: NoopEditGuard;
}

function textResult<TDetails extends Record<string, unknown> = Record<string, never>>(
  text: string,
  details?: TDetails
): { content: ToolContent; details: TDetails | Record<string, never> } {
  return { content: [{ type: 'text', text }], details: details ?? {} };
}

function errorResult(
  code: string,
  message: string,
  details: Record<string, unknown> = {}
): { content: ToolContent; details: Record<string, unknown> } {
  return textResult(message, { ok: false, error: code, message, ...details });
}

function resultDetails(result: FileMutationToolResult): MutationDetails {
  const details = result.details as unknown;
  return details && typeof details === 'object' ? (details as MutationDetails) : {};
}

function guardErrorDetails(
  guard: ReturnType<typeof validateMutationContent>,
  details: Record<string, unknown> = {}
): Record<string, unknown> {
  return {
    ...details,
    ...(guard?.details ?? {}),
  };
}

function validateUpdatedContent(
  filePath: string,
  content: string,
  details: Record<string, unknown> = {}
): { ok: true } | { ok: false; result: ReturnType<typeof errorResult> } {
  const guard = validateMutationContent(filePath, content);
  if (!guard) return { ok: true };
  return {
    ok: false,
    result: errorResult(guard.code, guard.message, guardErrorDetails(guard, details)),
  };
}

function suggestedActionForReadGuard(code: string): string {
  switch (code) {
    case 'file_not_read':
      return 'read_file';
    case 'partial_read':
      return 'read_full_file';
    case 'file_modified_since_read':
      return 'refresh_snapshot';
    default:
      return 'inspect_file_state';
  }
}

function readGuardFailureDetails(input: {
  code: string;
  relPath: string;
  currentContent?: string;
  readEntry?: ReadFileStateEntry;
  extra?: Record<string, unknown>;
}): Record<string, unknown> {
  return {
    path: input.relPath,
    retryable: true,
    suggestedAction: suggestedActionForReadGuard(input.code),
    state: buildFileStateErrorDescriptor({
      relPath: input.relPath,
      currentContent: input.currentContent,
      readContent: input.readEntry?.content,
      hasFullContent: input.readEntry?.hasFullContent,
      partialView: input.readEntry?.isPartialView,
    }),
    ...(input.extra ?? {}),
  };
}

function assertRebaseAnchorsWereRead(
  readContent: string | undefined,
  edits: BatchEditInput[]
): { ok: true } | { ok: false; code: string; message: string; details: Record<string, unknown> } {
  if (readContent === undefined) {
    return {
      ok: false,
      code: 'missing_read_snapshot',
      message: 'Cannot rebase because no previous read snapshot is available.',
      details: {},
    };
  }
  for (let index = 0; index < edits.length; index += 1) {
    const edit = edits[index];
    const actual = findActualString(readContent, edit.oldString);
    if (actual === null) {
      return {
        ok: false,
        code: 'not_found_in_read_snapshot',
        message: `edits[${index}].old_string was not present in the last Read snapshot.`,
        details: { editIndex: index },
      };
    }
    const occurrences = countOccurrences(readContent, actual);
    if (!edit.replaceAll && occurrences > 1) {
      return {
        ok: false,
        code: 'not_unique_in_read_snapshot',
        message: `edits[${index}].old_string appeared ${occurrences} times in the last Read snapshot.`,
        details: { editIndex: index, occurrences },
      };
    }
  }
  return { ok: true };
}

function toolParams(first: unknown, second: unknown): Record<string, unknown> {
  const candidate = second ?? first;
  return candidate && typeof candidate === 'object' ? (candidate as Record<string, unknown>) : {};
}

function truncateForModel(text: string, maxChars = MODEL_VISIBLE_DIFF_MAX_CHARS): string {
  if (text.length <= maxChars) return text;
  return `${text.slice(0, maxChars)}\n... [diff truncated, ${text.length - maxChars} chars omitted]`;
}

function truncateDiffDetail(diff: string): { diff: string; truncated: boolean } {
  if (diff.length <= DETAILS_DIFF_MAX_CHARS) return { diff, truncated: false };
  return {
    diff: `${diff.slice(0, DETAILS_DIFF_MAX_CHARS)}\n... [diff truncated, ${diff.length - DETAILS_DIFF_MAX_CHARS} chars omitted]`,
    truncated: true,
  };
}

function capStructuredPatchLines(hunks: FileDiffHunk[]): {
  structuredPatch: FileDiffHunk[];
  truncated: boolean;
} {
  let remaining = DETAILS_STRUCTURED_PATCH_MAX_LINES;
  let truncated = false;
  const structuredPatch: FileDiffHunk[] = [];
  for (const hunk of hunks) {
    if (remaining <= 0) {
      truncated = true;
      break;
    }
    if (hunk.lines.length <= remaining) {
      structuredPatch.push(hunk);
      remaining -= hunk.lines.length;
      continue;
    }
    structuredPatch.push({ ...hunk, lines: hunk.lines.slice(0, remaining) });
    truncated = true;
    remaining = 0;
  }
  return { structuredPatch, truncated };
}

function buildBudgetedDiffDetails(diff: FileDiffResult): {
  diff: string;
  structuredPatch: FileDiffHunk[];
  diffTruncated?: boolean;
  structuredPatchTruncated?: boolean;
} {
  const cappedDiff = truncateDiffDetail(diff.diff);
  const cappedPatch = capStructuredPatchLines(diff.structuredPatch);
  return {
    diff: cappedDiff.diff,
    structuredPatch: cappedPatch.structuredPatch,
    ...(cappedDiff.truncated ? { diffTruncated: true } : {}),
    ...(cappedPatch.truncated ? { structuredPatchTruncated: true } : {}),
  };
}

function buildMutationDetailsBase(input: {
  ok?: true;
  path: string;
  diff: FileDiffResult;
  extra?: Record<string, unknown>;
}): Record<string, unknown> {
  const diffDetails = buildBudgetedDiffDetails(input.diff);
  // Deliberately no full before/after content here: the diff + snapshot state
  // carry everything consumers use, and two file bodies per edit bloat every
  // persisted tool_call_record (~50KB each on a mid-sized file).
  return {
    ok: input.ok ?? true,
    path: input.path,
    ...(input.extra ?? {}),
    diff: diffDetails.diff,
    firstChangedLine: input.diff.firstChangedLine,
    structuredPatch: diffDetails.structuredPatch,
    lineChanges: input.diff.lineChanges,
    ...(diffDetails.diffTruncated ? { diffTruncated: true } : {}),
    ...(diffDetails.structuredPatchTruncated ? { structuredPatchTruncated: true } : {}),
  };
}

// Resolves the path that mutations should actually write through. For a regular
// file (or a not-yet-existing path) that's the path itself. For a symlink we
// follow it to its real target and write THROUGH the link — replacing the
// target's content via the usual temp+rename — instead of clobbering the link.
// Reads/stat already follow symlinks transparently, so the rest of the flow
// (snapshot, guards, backups) stays keyed on the original path. A symlink whose
// target escapes the workspace, or a broken link with no resolvable target, is
// refused: those are the cases where blindly following would be unsafe.
async function resolveWritePath(
  cwd: string,
  filePath: string,
  relPath: string
): Promise<
  | { ok: true; writePath: string; wasSymlink: boolean }
  | { ok: false; result: ReturnType<typeof errorResult> }
> {
  let linkStat;
  try {
    linkStat = await lstat(filePath);
  } catch (err) {
    if ((err as NodeJS.ErrnoException)?.code === 'ENOENT')
      return { ok: true, writePath: filePath, wasSymlink: false };
    throw err;
  }
  if (!linkStat.isSymbolicLink()) return { ok: true, writePath: filePath, wasSymlink: false };
  let target: string;
  try {
    target = await realpath(filePath);
  } catch {
    return {
      ok: false,
      result: errorResult(
        'broken_symlink',
        `Refusing to write through broken symlink: ${relPath}`,
        { path: relPath }
      ),
    };
  }
  // Compare the resolved target against the resolved workspace root, both
  // canonicalised, so symlinked workspace roots (macOS /tmp -> /private/tmp)
  // don't read as escapes. resolveInsideWorkspace can't be reused here: its fast
  // path compares an absolute argument against the raw, non-canonical cwd.
  const realWorkspace = await realpath(cwd).catch(() => path.resolve(cwd));
  const relToWorkspace = path.relative(realWorkspace, target);
  const insideWorkspace =
    relToWorkspace === '' || (!relToWorkspace.startsWith('..') && !path.isAbsolute(relToWorkspace));
  if (!insideWorkspace) {
    return {
      ok: false,
      result: errorResult(
        'symlink_escape',
        `Refusing to write through symlink whose target is outside the workspace: ${relPath}`,
        { path: relPath }
      ),
    };
  }
  return { ok: true, writePath: target, wasSymlink: true };
}

function formatLineChanges(lineChanges: unknown): string | undefined {
  if (!lineChanges || typeof lineChanges !== 'object') return undefined;
  const changes = lineChanges as { additions?: unknown; deletions?: unknown; changes?: unknown };
  if (typeof changes.additions !== 'number' || typeof changes.deletions !== 'number')
    return undefined;
  const total = typeof changes.changes === 'number' ? `, ${changes.changes} changed` : '';
  return `+${changes.additions} -${changes.deletions}${total}`;
}

function formatFirstChangedLine(value: unknown): string | undefined {
  return typeof value === 'number' ? String(value) : undefined;
}

function formatMutationStateLine(state: MutationStateDescriptor | undefined): string | undefined {
  if (!state) return undefined;
  const ranges =
    state.changedRanges.length > 0
      ? state.changedRanges.map(range => `${range.start}-${range.end}`).join(',')
      : 'none';
  const previous = state.previousSnapshotId ?? 'new-file';
  const rebase = state.rebased ? ' rebased=true;' : '';
  return `State:${rebase} previousSnapshotId=${previous} newSnapshotId=${state.newSnapshotId} changedRanges=${ranges}.`;
}

function formatPerFileResults(perFileResults: unknown): string[] {
  if (!Array.isArray(perFileResults) || perFileResults.length === 0) return [];
  return perFileResults.map((raw, index) => {
    const result = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {};
    const pathValue = typeof result.path === 'string' ? result.path : `operation ${index + 1}`;
    if (result.ok === false) {
      const error = typeof result.error === 'string' ? result.error : 'failed';
      const message = typeof result.message === 'string' ? `: ${result.message}` : '';
      return `- ${pathValue}: failed (${error})${message}`;
    }
    if (result.type === 'rename') {
      const originalPath =
        typeof result.originalPath === 'string' ? result.originalPath : pathValue;
      return `- rename ${originalPath} -> ${pathValue}`;
    }
    const type = typeof result.type === 'string' ? result.type : 'update';
    const firstChanged = formatFirstChangedLine(result.firstChangedLine);
    const changes = formatLineChanges(result.lineChanges);
    return [`- ${type} ${pathValue}`, firstChanged ? `line ${firstChanged}` : undefined, changes]
      .filter(Boolean)
      .join(' ');
  });
}

function buildMutationResultText(input: {
  action: string;
  path?: string;
  type?: string;
  preview?: boolean;
  replaced?: number;
  editCount?: number;
  fileCount?: number;
  firstChangedLine?: unknown;
  lineChanges?: unknown;
  diff?: string;
  perFileResults?: unknown;
  snapshotUpdated?: boolean;
  state?: MutationStateDescriptor;
  rebased?: boolean;
}): string {
  const headlineParts = [input.action];
  if (input.path) headlineParts.push(input.path);
  if (input.type) headlineParts.push(`(${input.type})`);

  const lines = [headlineParts.join(' ')];
  if (typeof input.fileCount === 'number') lines.push(`Files changed: ${input.fileCount}`);
  if (typeof input.editCount === 'number') lines.push(`Edits applied: ${input.editCount}`);
  if (typeof input.replaced === 'number') lines.push(`Replacements: ${input.replaced}`);

  const firstChanged = formatFirstChangedLine(input.firstChangedLine);
  if (firstChanged) lines.push(`First changed line: ${firstChanged}`);

  const changes = formatLineChanges(input.lineChanges);
  if (changes) lines.push(`Line changes: ${changes}`);

  if (input.rebased) {
    lines.push(
      'Rebased: file changed since the last Read, but each requested replacement still matched current content uniquely.'
    );
  }

  const stateLine = formatMutationStateLine(input.state);
  if (stateLine) lines.push(stateLine);

  const perFileLines = formatPerFileResults(input.perFileResults);
  if (perFileLines.length > 0) lines.push('Files:', ...perFileLines);

  if (input.preview) {
    lines.push('Disk: not modified (preview_only:true).');
  } else if (input.snapshotUpdated !== false) {
    lines.push(
      'Result: mutation is reflected in the diff below; do not call Read again only to verify it.'
    );
    lines.push('Snapshot: internal file state updated for subsequent Edit/Write calls.');
  } else if (!input.action.toLowerCase().includes('failed')) {
    lines.push(
      'Result: mutation is reflected in the diff below; do not call Read again only to verify it.'
    );
  }

  const diff = typeof input.diff === 'string' ? input.diff.trim() : '';
  lines.push(diff ? `Diff:\n${truncateForModel(diff)}` : 'Diff: (no textual changes)');
  return lines.join('\n');
}

function parseBatchEdits(
  value: unknown,
  options: { toolName?: string; minEdits?: number } = {}
):
  | { ok: true; edits: BatchEditInput[] }
  | { ok: false; code: string; message: string; details?: Record<string, unknown> }
  | undefined {
  if (value === undefined) return undefined;
  const toolName = options.toolName ?? 'Edit';
  const minEdits = options.minEdits ?? 1;
  if (!Array.isArray(value)) {
    return {
      ok: false,
      code: 'invalid_edits',
      message: `${toolName} edits must be an array of { old_string, new_string, replace_all? } objects`,
    };
  }
  if (value.length < minEdits) {
    return {
      ok: false,
      code: 'invalid_edits',
      message:
        minEdits === 1
          ? `${toolName} edits must include at least one replacement`
          : `${toolName} requires at least ${minEdits} replacements; use Edit for one exact replacement`,
      details: { editCount: value.length, minEdits },
    };
  }
  const edits: BatchEditInput[] = [];
  for (let index = 0; index < value.length; index += 1) {
    const entry = value[index];
    if (!entry || typeof entry !== 'object') {
      return {
        ok: false,
        code: 'invalid_edits',
        message: `${toolName} edits[${index}] must be an object`,
        details: { editIndex: index },
      };
    }
    const edit = entry as Record<string, unknown>;
    if (typeof edit.old_string !== 'string' || typeof edit.new_string !== 'string') {
      return {
        ok: false,
        code: 'missing_strings',
        message: `${toolName} edits[${index}] requires old_string and new_string`,
        details: { editIndex: index },
      };
    }
    if (edit.old_string === edit.new_string) {
      return {
        ok: false,
        code: 'no_op',
        message: `${toolName} edits[${index}].old_string and new_string are identical`,
        details: { editIndex: index },
      };
    }
    edits.push({
      oldString: edit.old_string,
      newString: edit.new_string,
      replaceAll: edit.replace_all === true,
    });
  }
  return { ok: true, edits };
}

async function runWithFileWriteLocks<T>(
  filePaths: string[],
  operation: () => Promise<T>
): Promise<T> {
  const uniquePaths = [...new Set(filePaths.map(filePath => path.resolve(filePath)))].sort();
  return uniquePaths.reduceRight(
    (next, filePath) => () => runWithFileWriteLock(filePath, next),
    operation
  )();
}

export function createWriteBridgeTool(cwd: string, options?: FileMutationToolOptions): AgentTool {
  return {
    name: 'Write',
    label: 'Write',
    description:
      'Write (create or overwrite) a file in the workspace. Creates parent directories as needed. Successful results include a model-visible diff and update the internal file snapshot, so do not call Read again only to verify the write.',
    parameters: {
      type: 'object',
      properties: {
        file_path: { type: 'string', description: 'Workspace-relative path of the file to write' },
        content: { type: 'string', description: 'Full file contents' },
      },
      required: ['file_path', 'content'],
    },
    execute: async (toolCallId: string, params: unknown) => {
      const args = toolParams(toolCallId, params);
      const requested = args.file_path;
      if (typeof requested !== 'string' || !requested.trim()) {
        return errorResult('missing_path', 'Write requires file_path');
      }
      if (typeof args.content !== 'string') {
        return errorResult('missing_content', 'Write requires string content');
      }
      const content = args.content;
      let filePath: string;
      try {
        filePath = resolveInsideWorkspace(cwd, requested);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const contentGuard = validateMutationContent(filePath, content);
      if (contentGuard) {
        return errorResult(
          contentGuard.code,
          contentGuard.message,
          guardErrorDetails(contentGuard, {
            path: toWorkspaceRelative(cwd, filePath),
          })
        );
      }
      const filenameMarker = findAutoGeneratedMarker(filePath, null);
      if (filenameMarker) {
        const relPath = toWorkspaceRelative(cwd, filePath);
        return errorResult(
          'auto_generated_file',
          buildAutoGeneratedMessage(relPath, filenameMarker),
          { path: relPath }
        );
      }
      try {
        return await runWithFileWriteLock(filePath, async () => {
          const relPathForSymlink = toWorkspaceRelative(cwd, filePath);
          const targetResult = await resolveWritePath(cwd, filePath, relPathForSymlink);
          if (!targetResult.ok) return targetResult.result;
          const writePath = targetResult.writePath;
          let existed = false;
          let originalContent: string | null = null;
          try {
            const targetStat = await stat(writePath);
            if (!targetStat.isFile()) {
              return errorResult('not_a_file', `Path is not a file: ${relPathForSymlink}`, {
                path: relPathForSymlink,
              });
            }
            existed = true;
          } catch (err) {
            const code = (err as NodeJS.ErrnoException)?.code;
            if (code !== 'ENOENT') throw err;
            // new file
          }
          let originalMetadata: Awaited<ReturnType<typeof readTextFileWithMetadata>> | undefined;
          if (existed) {
            originalMetadata = await readTextFileWithMetadata(writePath);
            originalContent = originalMetadata.content;
            const generatedMarker = findAutoGeneratedMarker(filePath, originalContent);
            if (generatedMarker) {
              const relPath = toWorkspaceRelative(cwd, filePath);
              return errorResult(
                'auto_generated_file',
                buildAutoGeneratedMessage(relPath, generatedMarker),
                { path: relPath }
              );
            }
            const readCheck = await options?.readFileState?.assertSafeToWrite(
              filePath,
              originalContent
            );
            if (readCheck && !readCheck.ok) {
              const relPath = toWorkspaceRelative(cwd, filePath);
              return errorResult(
                readCheck.code,
                readCheck.message,
                readGuardFailureDetails({
                  code: readCheck.code,
                  relPath,
                  currentContent: originalContent,
                  readEntry: options?.readFileState?.get(filePath),
                })
              );
            }
          }
          await mkdir(path.dirname(writePath), { recursive: true });
          const relPath = toWorkspaceRelative(cwd, filePath);
          const backup =
            originalContent !== null
              ? await recordFileBackup(relPath, originalContent, writePath)
              : undefined;
          const updatedContentForDisk =
            originalContent !== null
              ? applyLineEndingStyle(content, lineEndingFor(originalContent))
              : content;
          await writeTextFileAtomic(writePath, updatedContentForDisk, originalMetadata);
          const madeExecutable = await maybeMarkExecutableForShebang(writePath, content);
          await options?.readFileState?.recordWrite(filePath, content);
          options?.noopGuard?.clear(filePath);
          const diff =
            originalContent !== null
              ? buildFileDiff(relPath, originalContent, content)
              : buildFileDiff(relPath, '', content);
          const diffDetails = buildBudgetedDiffDetails(diff);
          const state = buildMutationStateDescriptor({
            relPath,
            originalContent,
            updatedContent: content,
            diff,
            snapshotUpdated: true,
          });
          const writeType = existed ? 'update' : 'create';
          const lifecycleInput = {
            operation: 'write',
            type: writeType,
            path: relPath,
            absolutePath: filePath,
            originalContent,
            updatedContent: content,
            diff: diff.diff,
            ...(diff.firstChangedLine !== undefined
              ? { firstChangedLine: diff.firstChangedLine }
              : {}),
          } as const;
          const lifecycle = mergeWriteLifecycleResults(
            await runWriteLifecycle(options?.writeLifecycle, lifecycleInput),
            options?.diagnosticsMode === 'deferred'
              ? scheduleDeferredDiagnostics(options?.diagnosticsProvider, lifecycleInput)
              : await runDiagnosticsProvider(options?.diagnosticsProvider, lifecycleInput)
          );
          const details = {
            ok: true,
            type: writeType,
            path: relPath,
            diff: diffDetails.diff,
            firstChangedLine: diff.firstChangedLine,
            structuredPatch: diffDetails.structuredPatch,
            lineChanges: diff.lineChanges,
            state,
            ...(diffDetails.diffTruncated ? { diffTruncated: true } : {}),
            ...(diffDetails.structuredPatchTruncated ? { structuredPatchTruncated: true } : {}),
            ...(backup ? { backup } : {}),
            ...(madeExecutable ? { madeExecutable: true } : {}),
            ...(lifecycle ? { lifecycle } : {}),
          };
          return textResult(
            buildMutationResultText({
              action: 'Wrote',
              path: relPath,
              type: writeType,
              diff: diff.diff,
              firstChangedLine: diff.firstChangedLine,
              lineChanges: diff.lineChanges,
              state,
            }),
            details
          );
        });
      } catch (err) {
        return errorResult('write_failed', err instanceof Error ? err.message : String(err), {
          path: String(requested),
        });
      }
    },
  } as unknown as AgentTool;
}

export function createEditBridgeTool(cwd: string, options?: FileMutationToolOptions): AgentTool {
  return {
    name: 'Edit',
    label: 'Edit',
    description:
      'Replace one exact string in an existing file. For two or more replacements in the same file, use MultiEdit so the file is read, checked, and written once; the batch is atomic and counts as one mutation attempt. This tool still accepts an `edits` array for compatibility, but new same-file batches should prefer MultiEdit. For small multi-file changes, use `patch`. For structurally-sensitive rewrites (Markdown tables, JSON arrays, indented YAML/TOML), prefer a single Write. Successful mutation results include a model-visible diff plus snapshot state, and update the internal file snapshot, so do not call Read again only to verify the edit.',
    parameters: {
      type: 'object',
      properties: {
        file_path: {
          type: 'string',
          description:
            'Workspace-relative path of the file to edit (required unless `patch` is given)',
        },
        old_string: {
          type: 'string',
          description:
            'Exact text to replace (required unless `patch` or `hashline_operation` is given)',
        },
        new_string: {
          type: 'string',
          description: 'Replacement text (required unless `patch` is given)',
        },
        replace_all: { type: 'boolean', default: false },
        edits: {
          type: 'array',
          description:
            'Compatibility path for same-file batch replacements. Prefer MultiEdit for two or more replacements in one file; all replacements apply atomically and consume one mutation attempt.',
          minItems: 1,
          items: {
            type: 'object',
            properties: {
              old_string: { type: 'string' },
              new_string: { type: 'string' },
              replace_all: { type: 'boolean', default: false },
            },
            required: ['old_string', 'new_string'],
          },
        },
        patch: {
          type: 'string',
          description:
            'Optional apply_patch-style multi-file patch. When provided, file_path/old_string/new_string are ignored.',
        },
        hashline_line: {
          type: 'string',
          description: 'Optional line hash from Read(hashline:true)',
        },
        hashline_operation: {
          type: 'string',
          description: 'Optional hashline operation, such as replace:<line-hash>',
        },
        hashline_tag: {
          type: 'string',
          description: 'Optional file-level tag from Read(hashline:true)',
        },
      },
    },
    execute: async (toolCallId: string, params: unknown) => {
      const args = toolParams(toolCallId, params);
      if (typeof args.patch === 'string' && args.patch.trim()) {
        try {
          const operations = parseApplyPatch(args.patch);
          const perFileResults: MutationDetails[] = [];
          const previewOnly = args.preview_only === true;
          if (!previewOnly) {
            const editTool = createEditBridgeTool(cwd, options);
            const preflight = await editTool.execute(`${toolCallId}:preflight`, {
              patch: args.patch,
              preview_only: true,
            });
            const preflightDetails = resultDetails(preflight);
            if (preflightDetails.ok === false) {
              return textResult(
                buildMutationResultText({
                  action: 'Patch failed preflight',
                  perFileResults: preflightDetails.perFileResults,
                  diff:
                    typeof preflightDetails.diff === 'string' ? preflightDetails.diff : undefined,
                  snapshotUpdated: false,
                }),
                {
                  ...preflightDetails,
                  preview: false,
                }
              );
            }
          }
          for (const operation of operations) {
            if (operation.type === 'add') {
              let filePath: string;
              try {
                filePath = resolveInsideWorkspace(cwd, operation.path);
              } catch (err) {
                const failure = {
                  ok: false,
                  error: 'path_outside_workspace',
                  message: err instanceof Error ? err.message : String(err),
                  path: operation.path,
                  type: 'create',
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              }
              const relPath = toWorkspaceRelative(cwd, filePath);
              const contentGuard = validateMutationContent(filePath, operation.content);
              if (contentGuard) {
                const failure = {
                  ok: false,
                  error: contentGuard.code,
                  message: contentGuard.message,
                  path: relPath,
                  type: 'create',
                  ...(contentGuard.details ?? {}),
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              }
              const filenameMarker = findAutoGeneratedMarker(filePath, null);
              if (filenameMarker) {
                const failure = {
                  ok: false,
                  error: 'auto_generated_file',
                  message: buildAutoGeneratedMessage(relPath, filenameMarker),
                  path: relPath,
                  type: 'create',
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              }
              let existed = false;
              let originalContent: string | null = null;
              try {
                // Symlinks are followed through to their target by the Write
                // tool (and by resolveWritePath); stat() here follows the link.
                const targetStat = await stat(filePath);
                if (!targetStat.isFile()) {
                  const failure = {
                    ok: false,
                    error: 'not_a_file',
                    message: `Path is not a file: ${relPath}`,
                    path: relPath,
                    type: 'create',
                  };
                  if (perFileResults.length === 0) return textResult(failure.message, failure);
                  perFileResults.push(failure);
                  break;
                }
                existed = true;
                const originalMetadata = await readTextFileWithMetadata(filePath);
                originalContent = originalMetadata.content;
                const generatedMarker = findAutoGeneratedMarker(filePath, originalContent);
                if (generatedMarker) {
                  const failure = {
                    ok: false,
                    error: 'auto_generated_file',
                    message: buildAutoGeneratedMessage(relPath, generatedMarker),
                    path: relPath,
                    type: 'create',
                  };
                  if (perFileResults.length === 0) return textResult(failure.message, failure);
                  perFileResults.push(failure);
                  break;
                }
                const readCheck = await options?.readFileState?.assertSafeToWrite(
                  filePath,
                  originalContent
                );
                if (readCheck && !readCheck.ok) {
                  const failure = {
                    ok: false,
                    error: readCheck.code,
                    message: readCheck.message,
                    path: relPath,
                    type: 'create',
                  };
                  if (perFileResults.length === 0) return textResult(failure.message, failure);
                  perFileResults.push(failure);
                  break;
                }
              } catch (err) {
                if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
              }
              if (previewOnly) {
                const diff = buildFileDiff(relPath, originalContent ?? '', operation.content);
                perFileResults.push({
                  ...buildMutationDetailsBase({
                    path: relPath,
                    diff,
                    extra: {
                      preview: true,
                      type: existed ? 'update' : 'create',
                    },
                  }),
                  preview: true,
                  type: existed ? 'update' : 'create',
                  path: relPath,
                });
                continue;
              }
              const writeTool = createWriteBridgeTool(cwd, options);
              const result = await writeTool.execute(`${toolCallId}:add:${operation.path}`, {
                file_path: operation.path,
                content: operation.content,
              });
              const details = resultDetails(result);
              if (details.ok === false) {
                if (perFileResults.length === 0) return result;
                perFileResults.push({ ...details, path: operation.path });
                break;
              }
              perFileResults.push({ ...details, path: operation.path });
              continue;
            }
            if (operation.type === 'delete') {
              const filePath = resolveInsideWorkspace(cwd, operation.path);
              const originalMetadata = await readTextFileWithMetadata(filePath);
              const original = originalMetadata.content;
              const generatedMarker = findAutoGeneratedMarker(filePath, original);
              if (generatedMarker) {
                const message = buildAutoGeneratedMessage(operation.path, generatedMarker);
                const failure = {
                  ok: false,
                  error: 'auto_generated_file',
                  message,
                  path: operation.path,
                  type: 'delete',
                };
                if (perFileResults.length === 0) return textResult(message, failure);
                perFileResults.push(failure);
                break;
              }
              const readCheck = await options?.readFileState?.assertSafeToWrite(filePath, original);
              if (readCheck && !readCheck.ok) {
                const failure = {
                  ok: false,
                  error: readCheck.code,
                  message: readCheck.message,
                  path: operation.path,
                  type: 'delete',
                };
                if (perFileResults.length === 0) return textResult(readCheck.message, failure);
                perFileResults.push(failure);
                break;
              }
              const diff = buildFileDiff(operation.path, original, '');
              const backup = previewOnly
                ? undefined
                : await recordFileBackup(operation.path, original, filePath);
              if (!previewOnly) {
                await runWithFileWriteLock(filePath, async () => {
                  await rm(filePath);
                });
                options?.noopGuard?.clear(filePath);
              }
              perFileResults.push({
                ...buildMutationDetailsBase({
                  path: operation.path,
                  diff,
                  extra: {
                    ...(previewOnly ? { preview: true } : {}),
                    type: 'delete',
                    ...(backup ? { backup } : {}),
                  },
                }),
                ...(previewOnly ? { preview: true } : {}),
                type: 'delete',
                path: operation.path,
                ...(backup ? { backup } : {}),
              });
              continue;
            }
            if (operation.type === 'rename') {
              const fromPath = resolveInsideWorkspace(cwd, operation.from);
              const toPath = resolveInsideWorkspace(cwd, operation.to);
              try {
                await stat(toPath);
                const failure = {
                  ok: false,
                  error: 'target_exists',
                  message: `Rename target already exists: ${operation.to}`,
                  path: operation.to,
                  originalPath: operation.from,
                  type: 'rename',
                };
                if (perFileResults.length === 0) return textResult(failure.message, failure);
                perFileResults.push(failure);
                break;
              } catch {
                // Target does not exist, so rename is allowed.
              }
              const originalMetadata = await readTextFileWithMetadata(fromPath);
              const original = originalMetadata.content;
              const generatedMarker = findAutoGeneratedMarker(fromPath, original);
              if (generatedMarker) {
                const message = buildAutoGeneratedMessage(operation.from, generatedMarker);
                const failure = {
                  ok: false,
                  error: 'auto_generated_file',
                  message,
                  path: operation.to,
                  originalPath: operation.from,
                  type: 'rename',
                };
                if (perFileResults.length === 0) return textResult(message, failure);
                perFileResults.push(failure);
                break;
              }
              const readCheck = await options?.readFileState?.assertSafeToWrite(fromPath, original);
              if (readCheck && !readCheck.ok) {
                const failure = {
                  ok: false,
                  error: readCheck.code,
                  message: readCheck.message,
                  path: operation.to,
                  originalPath: operation.from,
                  type: 'rename',
                };
                if (perFileResults.length === 0) return textResult(readCheck.message, failure);
                perFileResults.push(failure);
                break;
              }
              const backup = previewOnly
                ? undefined
                : await recordFileBackup(operation.from, original, fromPath);
              if (!previewOnly) {
                await runWithFileWriteLocks([fromPath, toPath], async () => {
                  await mkdir(path.dirname(toPath), { recursive: true });
                  await rename(fromPath, toPath);
                });
                await options?.readFileState?.recordWrite(toPath, original);
                options?.noopGuard?.clear(fromPath);
                options?.noopGuard?.clear(toPath);
              }
              perFileResults.push({
                ok: true,
                ...(previewOnly ? { preview: true } : {}),
                type: 'rename',
                path: operation.to,
                originalPath: operation.from,
                updatedContent: original,
                ...(backup ? { backup } : {}),
              });
              continue;
            }
            const editTool = createEditBridgeTool(cwd, options);
            const runUpdate = (oldText: string, newText: string, attempt: string) =>
              editTool.execute(`${toolCallId}:update:${operation.path}${attempt}`, {
                file_path: operation.path,
                old_string: oldText,
                new_string: newText,
                ...(previewOnly ? { preview_only: true } : {}),
              });
            let result = await runUpdate(operation.oldText, operation.newText, '');
            {
              const failed = resultDetails(result);
              // The parser always emits newline-terminated oldText/newText, so
              // a hunk anchored at EOF of a file without a trailing newline can
              // never match. Retry with the trailing newline dropped — only
              // when the target file itself ends without one, so mid-file
              // matches are unaffected.
              if (failed.ok === false && failed.error === 'not_found') {
                try {
                  const targetPath = resolveInsideWorkspace(cwd, operation.path);
                  const targetMetadata = await readTextFileWithMetadata(targetPath);
                  if (!targetMetadata.content.endsWith('\n')) {
                    result = await runUpdate(
                      operation.oldText.replace(/\n$/, ''),
                      operation.newText.replace(/\n$/, ''),
                      ':no-trailing-newline'
                    );
                  }
                } catch {
                  // Target unreadable or missing — keep the original failure.
                }
              }
            }
            const details = resultDetails(result);
            if (details.ok === false) {
              if (perFileResults.length === 0) return result;
              perFileResults.push({ ...details, type: 'update', path: operation.path });
              break;
            }
            perFileResults.push({ ...details, type: 'update', path: operation.path });
          }
          const failed = perFileResults.some(result => result.ok === false);
          const patchDiff = perFileResults
            .map(result => result.diff)
            .filter((diff): diff is string => typeof diff === 'string' && diff.length > 0)
            .join('\n');
          const patchDiffDetails = truncateDiffDetail(patchDiff);
          if (failed) {
            return textResult(
              buildMutationResultText({
                action: 'Patch partially failed',
                perFileResults,
                diff: patchDiff,
                snapshotUpdated: false,
              }),
              {
                ok: false,
                error: 'patch_partial_failure',
                perFileResults,
                ...(patchDiff ? { diff: patchDiffDetails.diff } : {}),
                ...(patchDiffDetails.truncated ? { diffTruncated: true } : {}),
              }
            );
          }
          return textResult(
            buildMutationResultText({
              action: previewOnly ? 'Previewed patch' : 'Applied patch',
              fileCount: perFileResults.length,
              perFileResults,
              diff: patchDiff,
              firstChangedLine: perFileResults.find(result => result.firstChangedLine !== undefined)
                ?.firstChangedLine,
              preview: previewOnly,
              snapshotUpdated: false,
            }),
            {
              ok: true,
              ...(previewOnly ? { preview: true } : {}),
              perFileResults,
              diff: patchDiffDetails.diff,
              ...(patchDiffDetails.truncated ? { diffTruncated: true } : {}),
              firstChangedLine: perFileResults.find(result => result.firstChangedLine !== undefined)
                ?.firstChangedLine,
            }
          );
        } catch (err) {
          return errorResult('patch_failed', err instanceof Error ? err.message : String(err));
        }
      }
      const requested = args.file_path;
      if (typeof requested !== 'string' || !requested.trim()) {
        return errorResult('missing_path', 'Edit requires file_path');
      }
      const batchEditsResult = parseBatchEdits(args.edits);
      if (batchEditsResult?.ok === false) {
        return errorResult(
          batchEditsResult.code,
          batchEditsResult.message,
          batchEditsResult.details ?? {}
        );
      }
      const batchEdits = batchEditsResult?.ok === true ? batchEditsResult.edits : undefined;
      const hashlineOperation = parseHashlineOperation(args.hashline_operation);
      const hashlineLine =
        hashlineOperation?.hash ??
        (typeof args.hashline_line === 'string' ? args.hashline_line.trim() : '');
      const isHashlineEdit = Boolean(hashlineLine);
      if (batchEdits && isHashlineEdit) {
        return errorResult(
          'invalid_edit_mode',
          'Edit cannot combine edits with hashline_operation/hashline_line'
        );
      }
      if (
        !isHashlineEdit &&
        !batchEdits &&
        (typeof args.old_string !== 'string' || typeof args.new_string !== 'string')
      ) {
        return errorResult('missing_strings', 'Edit requires old_string and new_string');
      }
      if (!isHashlineEdit && !batchEdits && args.old_string === args.new_string) {
        return errorResult('no_op', 'old_string and new_string are identical');
      }
      if (!batchEdits && typeof args.new_string !== 'string') {
        return errorResult('missing_strings', 'Edit requires new_string');
      }
      const newString = typeof args.new_string === 'string' ? args.new_string : '';
      const oldString = typeof args.old_string === 'string' ? args.old_string : '';
      const replaceAll = args.replace_all === true;
      let filePath: string;
      try {
        filePath = resolveInsideWorkspace(cwd, requested);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const replacementGuard = batchEdits
        ? batchEdits
            .map((edit, index) => ({
              index,
              guard: validateMutationContent(filePath, edit.newString),
            }))
            .find(entry => entry.guard)
        : { index: undefined, guard: validateMutationContent(filePath, newString) };
      if (replacementGuard?.guard) {
        return errorResult(
          replacementGuard.guard.code,
          replacementGuard.guard.message,
          guardErrorDetails(replacementGuard.guard, {
            path: toWorkspaceRelative(cwd, filePath),
            ...(replacementGuard.index !== undefined ? { editIndex: replacementGuard.index } : {}),
          })
        );
      }
      try {
        return await runWithFileWriteLock(filePath, async () => {
          const relPathForChecks = toWorkspaceRelative(cwd, filePath);
          const targetResult = await resolveWritePath(cwd, filePath, relPathForChecks);
          if (!targetResult.ok) return targetResult.result;
          const writePath = targetResult.writePath;
          const fileStat = await stat(filePath); // follows the symlink to its target
          if (!fileStat.isFile()) {
            return errorResult('not_a_file', `Path is not a file: ${relPathForChecks}`);
          }
          if (fileStat.size > MAX_EDIT_FILE_BYTES) {
            return errorResult(
              'file_too_large',
              `File is too large to edit safely: ${relPathForChecks}`,
              {
                path: relPathForChecks,
                size: fileStat.size,
                maxSize: MAX_EDIT_FILE_BYTES,
              }
            );
          }
          if (path.extname(filePath).toLowerCase() === '.ipynb') {
            return errorResult(
              'unsupported_notebook_edit',
              'Jupyter notebooks require a notebook-aware edit tool.',
              {
                path: relPathForChecks,
              }
            );
          }
          const originalMetadata = await readTextFileWithMetadata(filePath);
          const original = originalMetadata.content;
          const generatedMarker = findAutoGeneratedMarker(filePath, original);
          if (generatedMarker) {
            const relPath = toWorkspaceRelative(cwd, filePath);
            return errorResult(
              'auto_generated_file',
              buildAutoGeneratedMessage(relPath, generatedMarker),
              { path: relPath }
            );
          }
          // Hashline edits tolerate out-of-band drift: the content-hash anchor —
          // not the file-level tag or mtime — decides whether the edit is safe.
          let hashlineTagDrift = false;
          if (isHashlineEdit && typeof args.hashline_tag === 'string' && args.hashline_tag.trim()) {
            hashlineTagDrift = hashlineTag(original) !== args.hashline_tag.trim();
          }
          const readEntry = options?.readFileState?.get(filePath);
          const readCheck = isHashlineEdit
            ? options?.readFileState?.assertEditableHashline(filePath)
            : options?.readFileState?.assertEditable(filePath, original);
          let rebased = false;
          if (readCheck && !readCheck.ok) {
            const relPath = toWorkspaceRelative(cwd, filePath);
            if (!isHashlineEdit && readCheck.code === 'file_modified_since_read') {
              rebased = true;
            } else {
              return errorResult(
                readCheck.code,
                readCheck.message,
                readGuardFailureDetails({
                  code: readCheck.code,
                  relPath,
                  currentContent: original,
                  readEntry,
                })
              );
            }
          }
          const staleRebaseFailure = (
            code: string,
            message: string,
            details: Record<string, unknown> = {}
          ): ReturnType<typeof errorResult> => {
            const relPath = toWorkspaceRelative(cwd, filePath);
            if (!rebased) return errorResult(code, message, details);
            return errorResult(
              'file_modified_since_read',
              'File has changed since it was read and the requested edit could not be safely rebased. Read it again before editing.',
              readGuardFailureDetails({
                code: 'file_modified_since_read',
                relPath,
                currentContent: original,
                readEntry,
                extra: {
                  rebaseFailed: true,
                  rebaseError: code,
                  ...details,
                },
              })
            );
          };
          if (rebased) {
            const rebaseAnchorCheck = assertRebaseAnchorsWereRead(
              readEntry?.content,
              batchEdits ?? [{ oldString, newString, replaceAll }]
            );
            if (!rebaseAnchorCheck.ok) {
              return staleRebaseFailure(
                rebaseAnchorCheck.code,
                rebaseAnchorCheck.message,
                rebaseAnchorCheck.details
              );
            }
          }
          if (batchEdits) {
            const relPath = toWorkspaceRelative(cwd, filePath);
            let updated = original;
            let totalReplaced = 0;
            const appliedEdits: Array<{ index: number; replaced: number; replaceAll: boolean }> =
              [];
            for (let index = 0; index < batchEdits.length; index += 1) {
              const edit = batchEdits[index];
              const actual = findActualString(updated, edit.oldString);
              if (actual === null) {
                const ws = findWhitespaceMatch(updated, edit.oldString, edit.newString);
                if (ws.ok) {
                  updated =
                    updated.slice(0, ws.match.start) +
                    ws.match.adjustedNewString +
                    updated.slice(ws.match.end);
                  totalReplaced += 1;
                  appliedEdits.push({ index, replaced: 1, replaceAll: edit.replaceAll });
                  continue;
                }
                if (ws.reason === 'ambiguous') {
                  return staleRebaseFailure(
                    'not_unique',
                    `edits[${index}].old_string matches ${ws.count} locations after whitespace-normalization; add more surrounding context`,
                    { path: relPath, editIndex: index, occurrences: ws.count }
                  );
                }
                const attempts =
                  options?.noopGuard?.record(
                    filePath,
                    `batch_not_found:${index}:${hashlineForLine(edit.oldString)}`
                  ) ?? 0;
                if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                  return errorResult(
                    'edit_loop_detected',
                    `This batch edit has failed ${attempts} times — edits[${index}].old_string does not exist in ${relPath}. ` +
                      'Read the file again to see its current content before retrying.',
                    { path: relPath, editIndex: index, attempts }
                  );
                }
                return staleRebaseFailure(
                  'not_found',
                  `edits[${index}].old_string not found in file`,
                  { path: relPath, editIndex: index }
                );
              }
              const occurrences = countOccurrences(updated, actual);
              if (!edit.replaceAll && occurrences > 1) {
                return staleRebaseFailure(
                  'not_unique',
                  `edits[${index}].old_string appears ${occurrences} times; pass replace_all:true or add more context`,
                  {
                    path: relPath,
                    editIndex: index,
                    occurrences,
                  }
                );
              }
              const replaced = edit.replaceAll ? occurrences : 1;
              updated = applyEdit(updated, actual, edit.newString, edit.replaceAll);
              totalReplaced += replaced;
              appliedEdits.push({ index, replaced, replaceAll: edit.replaceAll });
            }

            if (updated === original) {
              const attempts =
                options?.noopGuard?.record(filePath, `batch_noop:${batchEdits.length}`) ?? 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This batch edit leaves ${relPath} unchanged and has been repeated ${attempts} times. ` +
                    'Read the file — the change may already be in place.',
                  { path: relPath, attempts }
                );
              }
              return errorResult('no_op', 'Batch edits leave the file unchanged', {
                path: relPath,
              });
            }

            const updatedGuard = validateUpdatedContent(filePath, updated, { path: relPath });
            if (!updatedGuard.ok) return updatedGuard.result;
            const diff = buildFileDiff(relPath, original, updated);
            const state = buildMutationStateDescriptor({
              relPath,
              originalContent: original,
              updatedContent: updated,
              diff,
              snapshotUpdated: args.preview_only !== true,
              readSnapshotContent: rebased ? readEntry?.content : undefined,
              rebased,
            });
            const detailsBase = buildMutationDetailsBase({
              path: relPath,
              diff,
              extra: {
                replaced: totalReplaced,
                editCount: batchEdits.length,
                edits: appliedEdits,
                state,
                ...(rebased ? { rebased: true } : {}),
              },
            });
            if (args.preview_only === true) {
              return textResult(
                buildMutationResultText({
                  action: 'Previewed edit',
                  path: relPath,
                  replaced: totalReplaced,
                  editCount: batchEdits.length,
                  diff: diff.diff,
                  firstChangedLine: diff.firstChangedLine,
                  lineChanges: diff.lineChanges,
                  preview: true,
                  snapshotUpdated: false,
                  state,
                  rebased,
                }),
                {
                  ...detailsBase,
                  preview: true,
                }
              );
            }

            const backup = await recordFileBackup(relPath, original, writePath);
            await writeTextFileAtomic(
              writePath,
              applyLineEndingStyle(updated, lineEndingFor(original)),
              originalMetadata
            );
            await options?.readFileState?.recordWrite(filePath, updated);
            options?.noopGuard?.clear(filePath);
            const lifecycleInput = {
              operation: 'edit',
              type: 'update',
              path: relPath,
              absolutePath: filePath,
              originalContent: original,
              updatedContent: updated,
              diff: diff.diff,
              ...(diff.firstChangedLine !== undefined
                ? { firstChangedLine: diff.firstChangedLine }
                : {}),
            } as const;
            const lifecycle = mergeWriteLifecycleResults(
              await runWriteLifecycle(options?.writeLifecycle, lifecycleInput),
              options?.diagnosticsMode === 'deferred'
                ? scheduleDeferredDiagnostics(options?.diagnosticsProvider, lifecycleInput)
                : await runDiagnosticsProvider(options?.diagnosticsProvider, lifecycleInput)
            );
            return textResult(
              buildMutationResultText({
                action: 'Edited',
                path: relPath,
                replaced: totalReplaced,
                editCount: batchEdits.length,
                diff: diff.diff,
                firstChangedLine: diff.firstChangedLine,
                lineChanges: diff.lineChanges,
                state,
                rebased,
              }),
              {
                ...detailsBase,
                backup,
                ...(lifecycle ? { lifecycle } : {}),
              }
            );
          }

          const actual = isHashlineEdit ? null : findActualString(original, oldString);
          if (isHashlineEdit) {
            // The snapshot (file as the model last saw it) disambiguates duplicate lines.
            const snapshot = options?.readFileState?.get(filePath)?.content;
            const updated = replaceHashlineLine(original, hashlineLine, newString, snapshot);
            const relPath = toWorkspaceRelative(cwd, filePath);
            if (updated === undefined) {
              const attempts =
                options?.noopGuard?.record(filePath, `hashline_mismatch:${hashlineLine}`) ?? 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This hashline edit has failed ${attempts} times — the anchored line no longer exists in ${relPath}. ` +
                    'Read the file again with hashline:true to get fresh anchors.',
                  { path: relPath, attempts }
                );
              }
              return errorResult(
                'hashline_mismatch',
                'hashline_line was not found in the current file' +
                  (hashlineTagDrift ? ' (the file has changed since it was read)' : ''),
                {
                  path: relPath,
                  retryable: true,
                  suggestedAction: 'refresh_hashline',
                  suggestion: 'Read the file again with hashline:true before editing.',
                  state: buildFileStateErrorDescriptor({
                    relPath,
                    currentContent: original,
                    readContent: readEntry?.content,
                    hasFullContent: readEntry?.hasFullContent,
                    partialView: readEntry?.isPartialView,
                  }),
                }
              );
            }
            const updatedGuard = validateUpdatedContent(filePath, updated, { path: relPath });
            if (!updatedGuard.ok) return updatedGuard.result;
            const diff = buildFileDiff(relPath, original, updated);
            const state = buildMutationStateDescriptor({
              relPath,
              originalContent: original,
              updatedContent: updated,
              diff,
              snapshotUpdated: args.preview_only !== true,
              readSnapshotContent: hashlineTagDrift ? readEntry?.content : undefined,
              rebased: hashlineTagDrift,
            });
            const hashlineDetailsBase = buildMutationDetailsBase({
              path: relPath,
              diff,
              extra: {
                replaced: 1,
                state,
                ...(hashlineTagDrift ? { rebased: true } : {}),
              },
            });
            if (args.preview_only === true) {
              return textResult(
                buildMutationResultText({
                  action: 'Previewed edit',
                  path: relPath,
                  replaced: 1,
                  diff: diff.diff,
                  firstChangedLine: diff.firstChangedLine,
                  lineChanges: diff.lineChanges,
                  preview: true,
                  snapshotUpdated: false,
                  state,
                  rebased: hashlineTagDrift,
                }),
                {
                  ...hashlineDetailsBase,
                  preview: true,
                  hashline: {
                    tag: hashlineTag(original),
                    ...(hashlineTagDrift ? { tagDrift: true } : {}),
                  },
                }
              );
            }
            if (updated === original) {
              const attempts = options?.noopGuard?.record(filePath, `noop:${hashlineLine}`) ?? 0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This edit leaves ${relPath} unchanged and has been repeated ${attempts} times. ` +
                    'Read the file — the change may already be in place.',
                  { path: relPath, attempts }
                );
              }
            } else {
              options?.noopGuard?.clear(filePath);
            }
            const backup = await recordFileBackup(relPath, original, writePath);
            await writeTextFileAtomic(
              writePath,
              applyLineEndingStyle(updated, lineEndingFor(original)),
              originalMetadata
            );
            await options?.readFileState?.recordWrite(filePath, updated);
            return textResult(
              buildMutationResultText({
                action: 'Edited',
                path: relPath,
                replaced: 1,
                diff: diff.diff,
                firstChangedLine: diff.firstChangedLine,
                lineChanges: diff.lineChanges,
                state,
                rebased: hashlineTagDrift,
              }),
              {
                ...hashlineDetailsBase,
                hashline: {
                  tag: hashlineTag(updated),
                  ...(hashlineTagDrift ? { tagDrift: true } : {}),
                },
                backup,
              }
            );
          }
          let updated: string;
          let replaced: number;
          let matchStrategy: 'exact' | 'quote' | 'whitespace';
          if (actual === null) {
            const relPathNF = toWorkspaceRelative(cwd, filePath);
            const ws = findWhitespaceMatch(original, oldString, newString);
            if (ws.ok) {
              updated =
                original.slice(0, ws.match.start) +
                ws.match.adjustedNewString +
                original.slice(ws.match.end);
              replaced = 1;
              matchStrategy = 'whitespace';
            } else if (ws.reason === 'ambiguous') {
              return staleRebaseFailure(
                'not_unique',
                `old_string matches ${ws.count} locations after whitespace-normalization; add more surrounding context`,
                { path: relPathNF, occurrences: ws.count }
              );
            } else {
              const attempts =
                options?.noopGuard?.record(filePath, `not_found:${hashlineForLine(oldString)}`) ??
                0;
              if (attempts >= NOOP_EDIT_HARD_LIMIT) {
                return errorResult(
                  'edit_loop_detected',
                  `This exact edit has failed ${attempts} times — old_string does not exist in ${relPathNF}. ` +
                    'Read the file again to see its current content before retrying.',
                  { path: relPathNF, attempts }
                );
              }
              return staleRebaseFailure('not_found', 'old_string not found in file', {
                path: relPathNF,
              });
            }
          } else {
            const occurrences = countOccurrences(original, actual);
            if (!replaceAll && occurrences > 1) {
              return staleRebaseFailure(
                'not_unique',
                `old_string appears ${occurrences} times; pass replace_all:true or add more context`,
                {
                  path: toWorkspaceRelative(cwd, filePath),
                  occurrences,
                }
              );
            }
            updated = applyEdit(original, actual, newString, replaceAll);
            replaced = replaceAll ? occurrences : 1;
            matchStrategy = actual === oldString ? 'exact' : 'quote';
          }
          const relPath = toWorkspaceRelative(cwd, filePath);
          const updatedGuard = validateUpdatedContent(filePath, updated, { path: relPath });
          if (!updatedGuard.ok) return updatedGuard.result;
          const diff = buildFileDiff(relPath, original, updated);
          const state = buildMutationStateDescriptor({
            relPath,
            originalContent: original,
            updatedContent: updated,
            diff,
            snapshotUpdated: args.preview_only !== true,
            readSnapshotContent: rebased ? readEntry?.content : undefined,
            rebased,
          });
          const detailsBase = buildMutationDetailsBase({
            path: relPath,
            diff,
            extra: {
              replaced,
              state,
              ...(rebased ? { rebased: true } : {}),
            },
          });
          if (args.preview_only === true) {
            return textResult(
              buildMutationResultText({
                action: 'Previewed edit',
                path: relPath,
                replaced,
                diff: diff.diff,
                firstChangedLine: diff.firstChangedLine,
                lineChanges: diff.lineChanges,
                preview: true,
                snapshotUpdated: false,
                state,
                rebased,
              }),
              {
                ...detailsBase,
                matchStrategy,
                preview: true,
              }
            );
          }
          const backup = await recordFileBackup(relPath, original, writePath);
          await writeTextFileAtomic(
            writePath,
            applyLineEndingStyle(updated, lineEndingFor(original)),
            originalMetadata
          );
          await options?.readFileState?.recordWrite(filePath, updated);
          if (updated !== original) options?.noopGuard?.clear(filePath);
          const lifecycleInput = {
            operation: 'edit',
            type: 'update',
            path: relPath,
            absolutePath: filePath,
            originalContent: original,
            updatedContent: updated,
            diff: diff.diff,
            ...(diff.firstChangedLine !== undefined
              ? { firstChangedLine: diff.firstChangedLine }
              : {}),
          } as const;
          const lifecycle = mergeWriteLifecycleResults(
            await runWriteLifecycle(options?.writeLifecycle, lifecycleInput),
            options?.diagnosticsMode === 'deferred'
              ? scheduleDeferredDiagnostics(options?.diagnosticsProvider, lifecycleInput)
              : await runDiagnosticsProvider(options?.diagnosticsProvider, lifecycleInput)
          );
          return textResult(
            buildMutationResultText({
              action: 'Edited',
              path: relPath,
              replaced,
              diff: diff.diff,
              firstChangedLine: diff.firstChangedLine,
              lineChanges: diff.lineChanges,
              state,
              rebased,
            }),
            {
              ...detailsBase,
              matchStrategy,
              backup,
              ...(lifecycle ? { lifecycle } : {}),
            }
          );
        });
      } catch (err) {
        return errorResult('edit_failed', err instanceof Error ? err.message : String(err), {
          path: String(requested),
        });
      }
    },
  } as unknown as AgentTool;
}

export function createMultiEditBridgeTool(
  cwd: string,
  options?: FileMutationToolOptions
): AgentTool {
  const editTool = createEditBridgeTool(cwd, options);
  return {
    ...editTool,
    name: 'MultiEdit',
    label: 'MultiEdit',
    description:
      'Apply two or more exact replacements to one existing workspace file atomically. This is the explicit form of Edit with an `edits` array; it reuses the same read-state, diff, backup, diagnostics, and snapshot behavior.',
    parameters: {
      type: 'object',
      properties: {
        file_path: { type: 'string', description: 'Workspace-relative path of the file to edit' },
        edits: {
          type: 'array',
          description:
            'Ordered same-file replacements. All replacements apply atomically and consume one mutation attempt.',
          minItems: 2,
          items: {
            type: 'object',
            properties: {
              old_string: { type: 'string' },
              new_string: { type: 'string' },
              replace_all: { type: 'boolean', default: false },
            },
            required: ['old_string', 'new_string'],
          },
        },
        preview_only: { type: 'boolean', default: false },
      },
      required: ['file_path', 'edits'],
    },
    execute: async (
      toolCallId: string,
      params: Parameters<FileMutationTool['execute']>[1],
      signal?: AbortSignal,
      onUpdate?: FileMutationToolUpdate
    ) => {
      const args = toolParams(toolCallId, params);
      const editsResult = parseBatchEdits(args.edits, { toolName: 'MultiEdit', minEdits: 2 });
      if (editsResult?.ok === false) {
        return errorResult(editsResult.code, editsResult.message, editsResult.details ?? {});
      }
      return editTool.execute(toolCallId, params, signal, onUpdate);
    },
  } as unknown as AgentTool;
}
