import type { AgentTool } from '@earendil-works/pi-agent-core';
import { validateToolArguments } from '@earendil-works/pi-ai';

/**
 * Per-run store carrying permission-approved argument rewrites from the
 * `beforeToolCall` hook to the tool's `execute`.
 *
 * Why this exists: `@earendil-works/pi-agent-core` (verified for 0.79.3 through
 * 0.81.1) declares `BeforeToolCallResult { block?, reason? }` only, and
 * `prepareToolCall` in `dist/agent-loop.js` reads only `block`/`reason` before
 * executing the tool with its own `validatedArgs`. Returning `{ args }` from
 * `beforeToolCall` is silently dropped, which made every `updatedInput`
 * producer (sudo credential rewrite, workflow approvals, auto-approvals) dead
 * code at runtime.
 *
 * Flow:
 * 1. `buildAgentHooks.beforeToolCall` records the approved `updatedInput`
 *    here, keyed by the pi tool-call id (`ctx.toolCall.id`), and still returns
 *    `{ args }` for forward compatibility.
 * 2. `buildTools` wraps every tool's `execute` via {@link withPendingArgOverrides};
 *    pi calls `execute(toolCall.id, validatedArgs, …)`, so the wrapper consumes
 *    the matching entry, re-validates it against the tool's own parameter
 *    schema (same `validateToolArguments` pi uses), and calls the real execute
 *    with the substituted args.
 *
 * Safety properties:
 * - One-shot: an entry is deleted when consumed, so overrides never leak into
 *   later calls — including retried calls that reuse the same tool name.
 * - Keyed by tool-call id (unique per call, generated by the model/provider),
 *   so parallel tool calls in one run cannot cross-substitute.
 * - TTL + bounded size: entries whose call was aborted between `beforeToolCall`
 *   and `execute` (pi drops prepared calls on abort) expire instead of leaking
 *   for the lifetime of the store.
 */
export class PendingArgOverrides {
  private readonly entries = new Map<string, { args: unknown; recordedAt: number }>();

  constructor(
    private readonly now: () => number = Date.now,
    private readonly ttlMs: number = DEFAULT_OVERRIDE_TTL_MS
  ) {}

  /** Record an approved rewrite for a pending tool call. Overwrites any stale entry for the same id. */
  record(toolCallId: string, args: unknown): void {
    this.sweepExpired();
    if (this.entries.size >= MAX_PENDING_OVERRIDES) {
      // Bounded growth: evict the oldest entry (Map preserves insertion order).
      const oldest = this.entries.keys().next().value;
      if (oldest !== undefined) this.entries.delete(oldest);
    }
    this.entries.set(toolCallId, { args, recordedAt: this.now() });
  }

  /** Take the rewrite for a tool call, deleting it (one-shot). Returns undefined when absent or expired. */
  consume(toolCallId: string): unknown {
    const entry = this.entries.get(toolCallId);
    if (!entry) return undefined;
    this.entries.delete(toolCallId);
    if (this.now() - entry.recordedAt > this.ttlMs) return undefined;
    return entry.args;
  }

  /** Visible for tests. */
  get size(): number {
    return this.entries.size;
  }

  private sweepExpired(): void {
    const now = this.now();
    for (const [id, entry] of this.entries) {
      if (now - entry.recordedAt > this.ttlMs) this.entries.delete(id);
    }
  }
}

export const DEFAULT_OVERRIDE_TTL_MS = 5 * 60 * 1000;
const MAX_PENDING_OVERRIDES = 256;

type ToolSignal = Parameters<AgentTool['execute']>[2];
type ToolUpdate = Parameters<AgentTool['execute']>[3];

/**
 * Wrap a tool so `execute` applies a pending permission-approved argument
 * override recorded for this tool-call id, then re-validates the substituted
 * args against the tool's parameter schema with the same validator pi applies
 * (`validateToolArguments` — TypeBox/JSON-schema coercion + check).
 *
 * Validation failure throws, which pi's `executePreparedToolCall` converts into
 * an error tool result — the same fail-closed behavior pi applies to invalid
 * model-supplied args. A permission-approved rewrite must never execute with
 * args the tool schema would reject.
 */
export function withPendingArgOverrides(
  tool: AgentTool,
  overrides: PendingArgOverrides
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
): AgentTool<any> {
  const originalExecute = tool.execute;
  return {
    ...tool,
    execute: async (
      toolCallId: string,
      params: unknown,
      signal?: ToolSignal,
      onUpdate?: ToolUpdate
    ) => {
      const pending = overrides.consume(toolCallId);
      if (pending === undefined) {
        return originalExecute(toolCallId, params, signal, onUpdate);
      }
      // pi validated the ORIGINAL args before beforeToolCall ran; the override
      // never passed through that path, so validate it here. Cast: pi's
      // ToolCall wants `arguments: Record<string, any>` while overrides are
      // produced as `unknown` by the permission layer.
      const validated = validateToolArguments(tool, {
        type: 'toolCall',
        id: toolCallId,
        name: tool.name,
        arguments: pending,
      } as Parameters<typeof validateToolArguments>[1]);
      return originalExecute(toolCallId, validated, signal, onUpdate);
    },
  };
}
