/**
 * RenameSymbol — rename a symbol everywhere the language server says it is
 * referenced, as one all-or-nothing write.
 *
 * A separate tool rather than an LSPTool action on purpose: LSPTool is
 * read-only (plan mode allows it), this writes. The permission prompt is the
 * Edit one, for the anchor file; the files the server adds are only known
 * once it answers, so each is checked here instead, and any that is outside
 * the workspace, in a dependency, sensitive or auto-generated refuses the
 * whole rename rather than prompting mid-call.
 *
 * Files the model has not Read are fine: the edits come from the server, over
 * content synced from disk just before, and a hash check under the write
 * locks catches a change in between.
 */
import type { AgentTool } from '@earendil-works/pi-agent-core';
import { readFile } from 'fs/promises';
import { isSensitiveFile } from '../../../utils/sensitive-files.js';
import { LanguageServerError, type LanguageServerPort } from '../language-server-port.js';
import { findAutoGeneratedMarker } from './auto-generated-guard.js';
import { applyFileEditsAtomically } from './edit-write/apply-text-edits.js';
import { buildMutationResultText, truncateDiffDetail } from './edit-write/mutation-details.js';
import {
  collectDiagnosticsReports,
  mergePerFileLifecycles,
} from './edit-write/patch-diagnostics.js';
import type { FileMutationToolOptions } from './edit-write/shared.js';
import { resolveColumn } from './lsp-tool.js';
import { agentToolParameters, errorResult, textResult, toolParams } from './tool-common.js';
import { resolveInsideWorkspace, toWorkspaceRelative } from './workspace-paths.js';

export interface RenameSymbolToolDeps {
  cwd: string;
  port?: LanguageServerPort;
  mutation?: FileMutationToolOptions;
}

const MAX_NAME_LENGTH = 200;

function parsePositive(value: unknown): number | undefined {
  const num = Number(value);
  return Number.isInteger(num) && num >= 1 ? num : undefined;
}

/** Why a file the rename touches may not be written, or undefined. */
async function refusalReason(
  cwd: string,
  file: string,
  external: boolean
): Promise<string | undefined> {
  if (external) return 'outside the workspace';
  try {
    resolveInsideWorkspace(cwd, file);
  } catch {
    return 'outside the workspace';
  }
  const relative = toWorkspaceRelative(cwd, file);
  if (relative.split('/').includes('node_modules')) return 'a dependency';
  if (isSensitiveFile(file)) return 'a sensitive file';
  try {
    if (findAutoGeneratedMarker(file, await readFile(file, 'utf8'))) return 'auto-generated';
  } catch {
    // Unreadable: the write step reports it.
  }
  return undefined;
}

export function createRenameSymbolTool(deps: RenameSymbolToolDeps): AgentTool {
  const { cwd, port, mutation } = deps;
  return {
    name: 'RenameSymbol',
    label: 'RenameSymbol',
    description: [
      'Rename a variable, function, class, method, type or other symbol everywhere it is referenced, using the workspace language server (semantic, so unrelated identifiers with the same text are left alone).',
      'Address any occurrence like LSPTool: file + line + symbol (the identifier as written on that line; add occurrence when it appears more than once), plus new_name. The rename happens at the declaration, so every reference in the workspace changes.',
      'All files change together or none do; files need not be Read first. It refuses when a reference sits outside the workspace, in a dependency, in a sensitive or auto-generated file; use Edit there.',
      'It renames code references only, not strings, comments or file names. Pass preview_only:true to see the files and diff without writing.',
      'The result reports type errors the rename introduced; a correct rename introduces none, so any error usually means the new name collides with or shadows another.',
    ].join(' '),
    parameters: agentToolParameters({
      type: 'object',
      properties: {
        file_path: {
          type: 'string',
          description:
            'File containing an occurrence of the symbol (workspace-relative or absolute)',
        },
        line: { type: 'integer', description: '1-based line of that occurrence' },
        symbol: { type: 'string', description: 'The current name, as written on that line' },
        occurrence: {
          type: 'integer',
          description: 'Which occurrence of symbol on the line (1-based, default 1)',
        },
        new_name: { type: 'string', description: 'The new name' },
        preview_only: { type: 'boolean', default: false },
      },
      required: ['file_path', 'line', 'symbol', 'new_name'],
      additionalProperties: false,
    }),
    execute: async (toolCallId: string, params: unknown, signal?: AbortSignal) => {
      const args = toolParams(toolCallId, params);
      if (!port?.rename) {
        return errorResult('lsp_unavailable', 'No language server is attached to this workspace');
      }
      const fileArg = typeof args.file_path === 'string' ? args.file_path.trim() : '';
      const symbol = typeof args.symbol === 'string' ? args.symbol.trim() : '';
      const newName = typeof args.new_name === 'string' ? args.new_name.trim() : '';
      const line = parsePositive(args.line);
      const occurrence = args.occurrence === undefined ? 1 : parsePositive(args.occurrence);
      const previewOnly = args.preview_only === true;
      if (!fileArg || !symbol || line === undefined || occurrence === undefined) {
        return errorResult(
          'invalid_arguments',
          'file_path, a 1-based line, symbol and (optionally) a 1-based occurrence are required'
        );
      }
      if (!newName || /\s/.test(newName) || newName.length > MAX_NAME_LENGTH) {
        return errorResult('invalid_name', 'new_name must be a single identifier without spaces');
      }
      if (newName === symbol.split('.').pop()) {
        return errorResult('invalid_name', 'new_name is the same as the current name');
      }

      let file: string;
      try {
        file = resolveInsideWorkspace(cwd, fileArg);
      } catch (err) {
        return errorResult(
          'path_outside_workspace',
          err instanceof Error ? err.message : String(err)
        );
      }
      const character = await resolveColumn(file, line, symbol, occurrence);
      if (typeof character !== 'number') {
        return errorResult('symbol_not_found', character.error, { line, symbol });
      }

      let computed;
      try {
        computed = await port.rename({ cwd, file, line, character, newName }, signal);
      } catch (err) {
        if (err instanceof LanguageServerError) return errorResult(err.code, err.message);
        return errorResult('request_failed', err instanceof Error ? err.message : String(err));
      }
      const oldName = computed.oldName ?? symbol.split('.').pop() ?? symbol;

      const refused: string[] = [];
      for (const target of computed.files) {
        const reason = await refusalReason(cwd, target.file, Boolean(target.external));
        if (reason) refused.push(`${target.path} (${reason})`);
      }
      if (refused.length > 0) {
        return errorResult(
          'rename_refused',
          `Renaming ${oldName} would also change ${refused.join(', ')}. Nothing was written. Rename the allowed occurrences with Edit, or leave this symbol as is.`,
          { refused }
        );
      }

      const applied = await applyFileEditsAtomically(
        computed.files.map(target => ({
          absolutePath: target.file,
          path: target.path,
          contentHash: target.contentHash,
          edits: target.edits,
        })),
        mutation,
        { previewOnly, cwd }
      );
      if (!applied.ok) {
        return errorResult(
          applied.error,
          applied.message,
          applied.path ? { path: applied.path } : {}
        );
      }

      const { perFileResults, diff } = applied;
      const editCount = computed.files.reduce((sum, target) => sum + target.edits.length, 0);
      const diagnosticsReports = collectDiagnosticsReports(perFileResults);
      const lifecycle = mergePerFileLifecycles(perFileResults);
      const introducedErrors = diagnosticsReports.some(
        entry => entry.report.errors.length > 0 || (entry.report.otherFiles?.errors.length ?? 0) > 0
      );
      const action = `${previewOnly ? 'Previewed rename' : 'Renamed'} ${oldName} → ${newName}`;
      const text = buildMutationResultText({
        action,
        fileCount: perFileResults.length,
        editCount,
        perFileResults,
        diff,
        preview: previewOnly,
        diagnosticsReports,
        notes: [
          ...(computed.skippedMissing?.length
            ? [
                `Skipped (no longer on disk, though the language server still listed them): ${computed.skippedMissing.join(', ')}.`,
              ]
            : []),
          ...(introducedErrors
            ? [
                'Note: a correct rename introduces no errors; these usually mean the new name collides with or shadows another symbol.',
              ]
            : []),
        ],
      });
      const diffDetails = truncateDiffDetail(diff);
      return textResult(text, {
        ok: true,
        ...(previewOnly ? { preview: true } : {}),
        symbol: oldName,
        newName,
        fileCount: perFileResults.length,
        editCount,
        perFileResults,
        diff: diffDetails.diff,
        ...(diffDetails.truncated ? { diffTruncated: true } : {}),
        ...(lifecycle ? { lifecycle } : {}),
      });
    },
  };
}
